version: '3.8'

volumes:
  mongodb_data_container:
  poster_api_node_modules:

services:

  # API
  api:
    build: ./
    command: npm start
    ports:
      - "5000:5000"
    volumes:
      - ./:/app/poster-api
      - poster_api_node_modules:/app/poster-api/node_modules
    environment:
      - MONGODB_URI=mongodb://admin:admin@mongo:27017/poster?authSource=admin
      - EXPRESS_PORT=5000

  # MongoDB
  mongo:
    image: mongo:6
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    
    

    