version: '3.8'

volumes:
  mongo:


services:
  # API
  service:
    container_name: poster-api
    build: ./
    command: /services/poster-api/entrypoint.sh
    ports:
      - "5000:5000"
    volumes:
      - ./:/services/poster-api

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
