version: '3.8'

services:

  # API
  api:
    build: ./
    command: yarn start
    ports:
      - "5000:5000"
    volumes:
      - ./:/app/poster-api
    environment:
      - MONGODB_URI=mongodb://admin:admin@localhost:27017/poster?authSource=admin
      - EXPRESS_PORT=5000

  # MongoDB
  mongo:
    image: mongo:6.0.1
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    stdin_open: true 
    tty: true
    
volumes:
  mongodb_data_container:

    