const { carBrands } = require("./carBrandsString")
const { phoneBrands } = require("./phoneBrandsString")
const { years } = require("./years")

module.exports.attributes = {
  // public
  price: {
    label: "price",
    formFieldType: "number",
    filterFieldType: "range",
    props: [
      { name: "suffix", value: "تومان" },
      { name: "min", value: "0" },
      { name: "max", value: "1000000000000" },
    ],
  },
  rentPrice: {
    label: "rent price",
    formFieldType: "number",
    filterFieldType: "range",
    props: [
      { name: "suffix", value: "تومان" },
      { name: "min", value: "0" },
      { name: "max", value: "1000000000000" },
    ],
  },
  depositPrice: {
    label: "deposit price",
    formFieldType: "number",
    filterFieldType: "range",
    props: [
      { name: "suffix", value: "تومان" },
      { name: "min", value: "0" },
      { name: "max", value: "1000000000000" },
    ],
  },
  status: {
    label: "status",
    formFieldType: "select",
    filterFieldType: "select",
    options: ["new", "like-new", "used", "repair-needed"],
  },
  hasImage: {
    label: "has image",
    filterFieldType: "checkbox",
  },
  // buildings
  rooms: {
    label: "rooms",
    formFieldType: "select",
    filterFieldType: "select",
    options: ["without room", "1", "2", "3", "4", "more than 4 room"],
  },
  buildingArea: {
    label: "building area",
    formFieldType: "number",
    filterFieldType: "range",
    props: [
      { name: "suffix", value: "square meter" },
      { name: "min", value: "1" },
      { name: "max", value: "10000" },
    ],
  },
  landArea: {
    label: "land area",
    formFieldType: "number",
    filterFieldType: "range",
    props: [
      { name: "suffix", value: "square meter" },
      { name: "min", value: "1" },
      { name: "max", value: "1000000" },
    ],
  },
  buildYear: {
    label: "build year",
    formFieldType: "select",
    options: years,
  },
  buildingAge: {
    label: "building age",
    formFieldType: "select",
    options: [
      "less-than-1-year",
      "less-than-2-year",
      "less-than-5-year",
      "less-than-10-year",
      "less-than-15-year",
      "less-than-20-year",
      "less-than-30-year",
      "more-than-30-year",
    ],
  },
  floor: {
    label: "floor",
    formFieldType: "select",
    filterFieldType: "select",
    options: [
      "basement",
      "ground",
      "first-floor",
      "second-floor",
      "third-floor",
      "fourth-floor",
      "fifth-floor",
      "sixth-floor",
      "seventh-floor",
      "eighth-floor",
      "ninth-floor",
      "tenth-floor",
      "upper-than-tenth-floor",
    ],
  },
  hasElevator: {
    label: "has elevator",
    formFieldType: "checkbox",
    filterFieldType: "checkbox",
  },
  hasStorage: {
    label: "has storage",
    formFieldType: "checkbox",
    filterFieldType: "checkbox",
  },
  hasParking: {
    label: "has parking",
    formFieldType: "checkbox",
    filterFieldType: "checkbox",
  },
  hasBalcony: {
    label: "has balcony",
    formFieldType: "checkbox",
    filterFieldType: "checkbox",
  },

  // vehicles
  carBrand: {
    label: "car brand",
    formFieldType: "select",
    filterFieldType: "select",
    options: carBrands,
    props: [
      { name: "withSearch", value: "1" },
      { name: "isNested", value: "1" },
    ],
  },
  productionYear: {
    label: "production year",
    formFieldType: "select",
    filterFieldType: "range",
    options: years,
  },
  bodyColor: {
    label: "body color",
    formFieldType: "select",
    filterFieldType: "select",
    options: ["black", "white", "silver", "grey", "blue", "red", "yellow", "green"],
  },
  usage: {
    label: "usage",
    formFieldType: "number",
    filterFieldType: "range",
    props: [
      { name: "suffix", value: "kilometer" },
      { name: "min", value: "0" },
      { name: "max", value: "1000000" },
    ],
  },
  bodyStatus: {
    label: "body status",
    formFieldType: "select",
    options: [
      "intact",
      "some-scratches",
      "paint-less-dent-removal",
      "some-paint",
      "half-paint",
      "full-paint",
      "accidental",
      "junk",
    ],
  },
  engineStatus: {
    label: "engine status",
    formFieldType: "select",
    options: ["healthy", "needs-repair", "replaced"],
  },
  chassisStatus: {
    label: "chassis status",
    formFieldType: "select",
    options: [
      "both-healthy",
      "back-damage",
      "back-paint",
      "front-damage",
      "front-paint",
      "back-damage-front-paint",
      "front-damage-back-paint",
      "both-damage",
      "both-paint",
    ],
  },
  gearbox: {
    label: "gearbox",
    formFieldType: "select",
    options: ["manual", "automatic"],
  },
  thirdPartyInsuranceDeadline: {
    label: "third party insurance deadline",
    formFieldType: "select",
    options: [
      "1-month",
      "2-month",
      "3-month",
      "4-month",
      "5-month",
      "6-month",
      "7-month",
      "8-month",
      "9-month",
      "10-month",
      "11-month",
      "12-month",
    ],
  },

  // phone
  phoneBrand: {
    label: "phone brand",
    formFieldType: "select",
    filterFieldType: "select",
    options: phoneBrands,
    props: [
      { name: "withSearch", value: "1" },
      { name: "isNested", value: "1" },
    ],
  },
  simCardSlot: {
    label: "sim card slot",
    formFieldType: "select",
    filterFieldType: "select",
    options: ["1-slot", "2-slot", "3-slot-and-more"],
  },
  originality: {
    label: "originality",
    formFieldType: "select",
    filterFieldType: "select",
    options: ["original", "fake"],
  },
  ramMemory: {
    label: "ram memory",
    formFieldType: "select",
    filterFieldType: "select",
    options: [
      "irrelevant",
      "512MB",
      "768MB",
      "1GB",
      "1.5GB",
      "2GB",
      "3GB",
      "4GB",
      "6GB",
      "8GB",
      "10GB",
      "12GB",
      "16GB",
      "18GB",
    ],
  },
  internalStorage: {
    label: "internal storage",
    formFieldType: "select",
    filterFieldType: "select",
    options: [
      "irrelevant",
      "512MB",
      "1GB",
      "2GB",
      "3GB",
      "4GB",
      "8GB",
      "13GB",
      "16GB",
      "20GB",
      "32GB",
      "64GB",
      "128GB",
      "256GB",
      "512GB",
      "1TB",
    ],
  },
}
