module.exports.carBrands = [
  "Audi",
  "Audi Q5",
  "Audi TT",
  "Audi TT convertible",
  "Audi TT coupe",
  "Arisan",
  "Ario",
  "Ario automatic-1600cc",
  "Ario manual-1500cc",
  "Ario manual-1600cc",
  "Alfa Romeo",
  "Alfa Romeo 4C",
  "Alfa Romeo Giulietta",
  "Alfa Romeo MiTo",
  "Amico",
  "Opel",
  "Opel Astra Station",
  "Opel Astra",
  "Opel Astra new",
  "Opel Astra old",
  "Opel Astra Hatchback",
  "Opel Astra Hatchback 1400cc",
  "Opel Astra Hatchback 1600cc",
  "Opel Omega",
  "Opel Insignia",
  "Opel Calibra",
  "Opel Corsa",
  "Opel Corsa automatic",
  "Opel Corsa new",
  "Opel Corsa old",
  "Opel Mokka",
  "Opel Vectra",
  "SWM",
  "SWM G01",
  "SWM G01 F",
  "Smart",
  "Smart Fortwo",
  "Smart Forfour",
  "Oldsmobile",
  "Oldsmobile Regency",
  "Oldsmobile Cutlass",
  "MG",
  "MG 3",
  "MG 350",
  "MG 360",
  "MG 360 automatic",
  "MG 360 automatic-turbo",
  "MG 360 manual",
  "MG 550",
  "MG 6",
  "MG 6 Magnette",
  "MG 6 New",
  "MG 6 GT",
  "MG GS",
  "MG GT",
  "MG RX5",
  "MVM",
  "MVM 110",
  "MVM 110 3 cylinder",
  "MVM 110 automatic-4 cylinder",
  "MVM 110 manual-4 cylinder",
  "MVM 110S",
  "MVM 110S sport-luxury",
  "MVM 110S comfort",
  "MVM 110S luxury",
  "MVM 315 Sedan",
  "MVM 315 Sedan sedan-sport",
  "MVM 315 Sedan basic",
  "MVM 315 hatchback",
  "MVM 315 hatchback sport-excellent",
  "MVM 315 hatchback sport-luxury",
  "MVM 315 Hatchback Plus",
  "MVM 315 hatchback basic",
  "MVM 530",
  "MVM 550",
  "MVM 550 automatic",
  "MVM 550 manual",
  "MVM X22",
  "MVM X22 automatic-sport",
  "MVM X22 automatic-sport-excellent",
  "MVM X22 automatic-sport-luxury",
  "MVM X22 automatic",
  "MVM X22 automatic-luxury",
  "MVM X22 manual-sport-excellent",
  "MVM X22 manual-sport-luxury",
  "MVM X22 manual-basic",
  "MVM X22 manual-luxury",
  "MVM X22pro",
  "MVM X22pro Excellent",
  "MVM X22pro IE",
  "MVM X33",
  "MVM X33 automatic",
  "MVM X33 manual",
  "MVM X33S",
  "MVM X33S sport",
  "MVM X33S basic",
  "MVM X33S New Face",
  "MVM X55",
  "MVM X55 Excellent",
  "MVM X55 Excellent-sport",
  "MVM X55 Pro",
  "MVM X55 Pro Excellent",
  "MVM X55 Pro Excellent-sport",
  "Isuzu",
  "Isuzu Double Cabin",
  "Isuzu Double Cabin D Max",
  "inroads",
  "inroads Van C35",
  "Iveco",
  "BAIC",
  "BAIC Sabrina",
  "BAIC Sabrina-ir",
  "BAIC Sabrina-ir hatchback",
  "BAIC Sabrina hatchback",
  "BAIC Senova",
  "BAIC X25",
  "BAIC X25 Automatic",
  "BAIC X25 Manual",
  "Brilliance",
  "Brilliance C3",
  "Brilliance C3 automatic-1500cc",
  "Brilliance C3 automatic-1650cc",
  "Brilliance H220",
  "Brilliance H220 automatic",
  "Brilliance H220 manual",
  "Brilliance H230",
  "Brilliance H230 automatic",
  "Brilliance H230 manual",
  "Brilliance H320",
  "Brilliance H320 automatic-1500cc",
  "Brilliance H320 automatic-1650cc",
  "Brilliance H320 manual-1500cc",
  "Brilliance H320 manual-1650cc",
  "Brilliance H330",
  "Brilliance H330 automatic-1500cc",
  "Brilliance H330 automatic-1650cc",
  "Brilliance H330 manual-1500cc",
  "Brilliance H330 manual-1650cc",
  "Brilliance V5",
  "Besturn",
  "Besturn B30",
  "Besturn B50",
  "Besturn B50F",
  "Mercedes-Benz",
  "Mercedes-Benz A Class",
  "Mercedes-Benz A Class A150",
  "Mercedes-Benz A Class A170",
  "Mercedes-Benz A Class A200",
  "Mercedes-Benz A Class A200-turbo",
  "Mercedes-Benz B Class",
  "Mercedes-Benz B Class B200",
  "Mercedes-Benz B Class B200-turbo",
  "Mercedes-Benz C Class",
  "Mercedes-Benz C Class Coupe",
  "Mercedes-Benz C Class Coupe C230",
  "Mercedes-Benz C Class Coupe C250",
  "Mercedes-Benz C Class Coupe C350",
  "Mercedes-Benz C Class C180",
  "Mercedes-Benz C Class C200",
  "Mercedes-Benz C Class C230",
  "Mercedes-Benz C Class C240-automatic",
  "Mercedes-Benz C Class C240-manual",
  "Mercedes-Benz C Class C250",
  "Mercedes-Benz C Class C280",
  "Mercedes-Benz C Class C300",
  "Mercedes-Benz C Class C350",
  "Mercedes-Benz CL Class",
  "Mercedes-Benz CL Class CL500",
  "Mercedes-Benz CLA Class",
  "Mercedes-Benz CLA Class CLA45",
  "Mercedes-Benz CLK Class convertible",
  "Mercedes-Benz CLK Class convertible CLK200",
  "Mercedes-Benz CLK Class convertible CLK240",
  "Mercedes-Benz CLK Class convertible CLK280",
  "Mercedes-Benz CLK Class Coupe",
  "Mercedes-Benz CLK Class Coupe CLK200",
  "Mercedes-Benz CLS Class",
  "Mercedes-Benz CLS Class CLS350",
  "Mercedes-Benz CLS Class CLS500",
  "Mercedes-Benz CLS Class CLS550",
  "Mercedes-Benz E Class",
  "Mercedes-Benz E Class Convertible",
  "Mercedes-Benz E Class Convertible E200",
  "Mercedes-Benz E Class Convertible E250",
  "Mercedes-Benz E Class Convertible E350",
  "Mercedes-Benz E Class Coupe",
  "Mercedes-Benz E Class Coupe E200",
  "Mercedes-Benz E Class Coupe E250",
  "Mercedes-Benz E Class Coupe E350",
  "Mercedes-Benz E Class-ir",
  "Mercedes-Benz E Class-ir E200",
  "Mercedes-Benz E Class-ir E280",
  "Mercedes-Benz E Class-ir E350",
  "Mercedes-Benz E Class E190",
  "Mercedes-Benz E Class E200",
  "Mercedes-Benz E Class E220",
  "Mercedes-Benz E Class E230",
  "Mercedes-Benz E Class E240-automatic",
  "Mercedes-Benz E Class E240-manual",
  "Mercedes-Benz E Class E250",
  "Mercedes-Benz E Class E280",
  "Mercedes-Benz E Class E300",
  "Mercedes-Benz E Class E350",
  "Mercedes-Benz GLA Class",
  "Mercedes-Benz GLA Class GLA250",
  "Mercedes-Benz GLA Class GLA45",
  "Mercedes-Benz GLK Class",
  "Mercedes-Benz GLK Class GLK350",
  "Mercedes-Benz ML Class",
  "Mercedes-Benz ML Class ML350",
  "Mercedes-Benz S Class",
  "Mercedes-Benz S Class S280",
  "Mercedes-Benz S Class S300",
  "Mercedes-Benz S Class S320",
  "Mercedes-Benz S Class S350",
  "Mercedes-Benz S Class S500",
  "Mercedes-Benz S Class SE",
  "Mercedes-Benz SL Class",
  "Mercedes-Benz SL Class SL350",
  "Mercedes-Benz SL Class SL500",
  "Mercedes-Benz SLC Class",
  "Mercedes-Benz SLK Class",
  "Mercedes-Benz SLK Class SLK200",
  "Mercedes-Benz SLK Class SLK280",
  "Mercedes-Benz SLK Class SLK350",
  "Mercedes-Benz Classic",
  "Borgward",
  "Borgward BX5",
  "Borgward BX5 Ultimate",
  "Borgward BX7",
  "Borgward BX7 Ultimate",
  "BMW",
  "BMW 2002",
  "BMW 1 Series Convertible",
  "BMW 1 Series Convertible 120i",
  "BMW 1 Series Convertible 125i",
  "BMW 1 Series Coupe",
  "BMW 1 Series Hatchback",
  "BMW 1 Series Hatchback 118i",
  "BMW 1 Series Hatchback 120i",
  "BMW 1 Series Hatchback 125i",
  "BMW 2 Series Activetourer",
  "BMW 2 Series Activetourer 218i",
  "BMW 2 Series Convertible",
  "BMW 2 Series Convertible 220i",
  "BMW 2 Series Convertible 230i",
  "BMW 2 Series Coupe",
  "BMW 2 Series Coupe 220i",
  "BMW 2 Series Coupe 230i",
  "BMW 3 Series Sedan",
  "BMW 3 Series Sedan 316i",
  "BMW 3 Series Sedan 318i-automatic",
  "BMW 3 Series Sedan 318i-manual",
  "BMW 3 Series Sedan 320i",
  "BMW 3 Series Sedan 325i",
  "BMW 3 Series Sedan 328i",
  "BMW 3 Series Sedan 330i",
  "BMW 3 Series Convertible",
  "BMW 3 Series Convertible 320i",
  "BMW 3 Series Convertible 325i",
  "BMW 3 Series Convertible 330i",
  "BMW 3 Series Convertible 335i",
  "BMW 3 Series Coupe",
  "BMW 3 Series Coupe 320i",
  "BMW 3 Series Coupe 325i",
  "BMW 3 Series Coupe 330i",
  "BMW 3 Series Coupe 335i",
  "BMW 3 Series GT",
  "BMW 3 Series GT 328i",
  "BMW 4 Series Convertible",
  "BMW 4 Series Convertible 428i",
  "BMW 4 Series Coupe",
  "BMW 4 Series Coupe 420i",
  "BMW 4 Series Coupe 428i",
  "BMW 4 Series Grancoupe",
  "BMW 4 Series Grancoupe 420i",
  "BMW 4 Series Grancoupe 428i",
  "BMW 5 Series Sedan",
  "BMW 5 Series Sedan 518",
  "BMW 5 Series Sedan 520i",
  "BMW 5 Series Sedan 523i",
  "BMW 5 Series Sedan 525i",
  "BMW 5 Series Sedan 528i",
  "BMW 5 Series Sedan 530i",
  "BMW 5 Series Sedan 530xi",
  "BMW 5 Series Sedan 535i",
  "BMW 5 Series Sedan 540i",
  "BMW 5 Series Sedan 550i",
  "BMW 5 Series GT",
  "BMW 5 Series GT 528i",
  "BMW 5 Series GT 535i",
  "BMW 6 Series Convertible",
  "BMW 6 Series Convertible 630i",
  "BMW 6 Series Convertible 650i",
  "BMW 6 Series Convertible M6",
  "BMW 6 Series Coupe",
  "BMW 6 Series Coupe 630i",
  "BMW 6 Series Coupe 640i",
  "BMW 6 Series Coupe 650i",
  "BMW 6 Series Grancoupe",
  "BMW 6 Series Grancoupe 640i",
  "BMW 6 Series Grancoupe 650i",
  "BMW 6 Series Grancoupe M6",
  "BMW 7 Series",
  "BMW 7 Series 730i",
  "BMW 7 Series 730li",
  "BMW 7 Series 740li",
  "BMW 7 Series 750li",
  "BMW Classic",
  "BMW i8",
  "BMW X1",
  "BMW X1 18i",
  "BMW X1 20i",
  "BMW X1 25i",
  "BMW X1 28i",
  "BMW X3",
  "BMW X3 25i",
  "BMW X3 28i",
  "BMW X3 30i",
  "BMW X3 35i",
  "BMW X4",
  "BMW X4 28i",
  "BMW X5",
  "BMW X5 50i",
  "BMW X6",
  "BMW X6 35i",
  "BMW X6 50i",
  "BMW Z3",
  "BMW Z4",
  "BMW Z4 20i",
  "BMW Z4 23i",
  "BMW Z4 28i",
  "BMW Z4 30i",
  "BMW Z4 35i",
  "BISU",
  "BISU T3",
  "BISU T5",
  "BYD",
  "BYD F3",
  "BYD S6",
  "BYD S7",
  "Buick",
  "Buick B2",
  "Buick B3",
  "Buick B3-ir",
  "Pazhan",
  "Pazhan 2 door",
  "Pazhan 4 door",
  "Pazhan 4 door 4 cylinder-4 door",
  "Pazhan 4 door 6 cylinder-4 door",
  "Pazhan Herour",
  "Pride",
  "Pride 111",
  "Pride 111 EX",
  "Pride 111 SE",
  "Pride 111 SL",
  "Pride 111 SX",
  "Pride 131",
  "Pride 131 Bi-fuel",
  "Pride 131 EX",
  "Pride 131 LE",
  "Pride 131 SE",
  "Pride 131 SL",
  "Pride 131 SX",
  "Pride 131 TL",
  "Pride 132",
  "Pride 132 Bi-fuel",
  "Pride 132 basic",
  "Pride 132 EX",
  "Pride 132 SE",
  "Pride 132 SL",
  "Pride 132 SX",
  "Pride 141",
  "Pride 141 Bi-fuel",
  "Pride 141 basic",
  "Pride 141 EX",
  "Pride 141 SE",
  "Pride 141 SX",
  "Pride Automatic",
  "Pride Station",
  "Pride Sedan",
  "Pride Sedan petrol",
  "Pride Sedan CNG",
  "Pride Sedan LPG",
  "Pride Hatchback",
  "Proton",
  "Proton Impian",
  "Proton Gen-2",
  "Proton Gen-2 automatic",
  "Proton Gen-2 manual",
  "Proton Viera",
  "Proton Viera automatic",
  "Proton Viera manual",
  "Peugeot",
  "Peugeot 2008",
  "Peugeot 205",
  "Peugeot 206",
  "Peugeot 206 1",
  "Peugeot 206 2",
  "Peugeot 206 3",
  "Peugeot 206 3P",
  "Peugeot 206 4",
  "Peugeot 206 5",
  "Peugeot 206 6",
  "Peugeot 206 SD",
  "Peugeot 206 SD V1",
  "Peugeot 206 SD V10",
  "Peugeot 206 SD V19",
  "Peugeot 206 SD V2",
  "Peugeot 206 SD V20",
  "Peugeot 206 SD V6",
  "Peugeot 206 SD V8",
  "Peugeot 206 SD V9",
  "Peugeot 207i",
  "Peugeot 207i automatic",
  "Peugeot 207i automatic MC",
  "Peugeot 207i Automatic P",
  "Peugeot 207i Manual P",
  "Peugeot 207i manual",
  "Peugeot 207i SD",
  "Peugeot 207i SD automatic",
  "Peugeot 207i SD manual",
  "Peugeot 301",
  "Peugeot 404",
  "Peugeot 405",
  "Peugeot 405 station",
  "Peugeot 405 GLX-TU5-Petrol",
  "Peugeot 405 GLX-TU5-Bi-fuel",
  "Peugeot 405 GL-Bi-fuel(CNG)",
  "Peugeot 405 GL-Bi-fuel(LPG)",
  "Peugeot 405 GL-petrol",
  "Peugeot 405 GLi-Bi-fuel(CNG)",
  "Peugeot 405 GLi-Bi-fuel(LPG)",
  "Peugeot 405 GLi-petrol",
  "Peugeot 405 GLX-Bi-fuel(CNG)",
  "Peugeot 405 GLX-Bi-fuel(LPG)",
  "Peugeot 405 GLX-petrol",
  "Peugeot 405 SLX",
  "Peugeot 405 SLX-Bi-fuel",
  "Peugeot 406",
  "Peugeot 407",
  "Peugeot 504",
  "Peugeot 508",
  "Peugeot 508 GT",
  "Peugeot Pars",
  "Peugeot Pars automatic-TU5",
  "Peugeot Pars Bi-fuel",
  "Peugeot Pars basic",
  "Peugeot Pars latest",
  "Peugeot Limousine",
  "Peugeot Pars XU7P",
  "Peugeot Pars XU7P-ELX",
  "Peugeot Pars ELX",
  "Peugeot Pars ELX-TU5",
  "Peugeot Pars ELX XUM",
  "Peugeot Pars LX-TU5",
  "Peugeot Roa",
  "Peugeot Roa Petrol",
  "Peugeot Roa Bi-fuel",
  "Peugeot Roa Sal",
  "Peugeot Roa Sal petrol",
  "Peugeot Roa Sal Bi-fuel",
  "Peugeot RD",
  "Peugeot RD petrol",
  "Peugeot RD Bi-fuel(CNG)",
  "Peugeot RD Bi-fuel(LPG)",
  "Peugeot RDI",
  "Peugeot RDI petrol",
  "Porsche",
  "Porsche 911",
  "Porsche 911 Carrera 4",
  "Porsche 911 Carrera S",
  "Porsche Boxster",
  "Porsche Boxster 718",
  "Porsche Boxster 718 S",
  "Porsche Boxster V6",
  "Porsche Boxster V6 S",
  "Porsche Panamera",
  "Porsche Panamera 4S",
  "Porsche Panamera 4S turbo",
  "Porsche Panamera V6",
  "Porsche Cayenne",
  "Porsche Cayenne GTS",
  "Porsche Cayenne S",
  "Porsche Cayenne S turbo",
  "Porsche Cayenne V6",
  "Porsche Cayman",
  "Porsche Cayman S",
  "Porsche Macan",
  "Pontiac",
  "Pontiac Parisienne",
  "Pontiac Grandprix",
  "Rich Rich",
  "Paykan",
  "Paykan Petrol",
  "Paykan Bi-fuel(CNG)",
  "Paykan Bi-fuel(LPG)",
  "Paykan Pickup",
  "Paykan Pickup Petrol",
  "Paykan Pickup CNG",
  "Paykan Pickup LPG",
  "Tara",
  "Tara Automatic",
  "Tara Manual",
  "Toyota",
  "Toyota Aurion",
  "Toyota Aurion sport",
  "Toyota Aurion grand",
  "Toyota FJ Cruiser",
  "Toyota Echo",
  "Toyota Prado 2door",
  "Toyota Prado 2door 4 cylinder",
  "Toyota Prado 2door 6 cylinder",
  "Toyota Prado 4door",
  "Toyota Prado 4door 4 cylinder",
  "Toyota Prado 4door 6 cylinder",
  "Toyota Prado 4door 6 cylinder-off road",
  "Toyota Prado 4door 6 cylinder-on road",
  "Toyota Prius",
  "Toyota Prius 2",
  "Toyota Prius 3",
  "Toyota Prius A",
  "Toyota Prius B",
  "Toyota Prius C",
  "Toyota Rav4",
  "Toyota Celica",
  "Toyota Supra",
  "Toyota Solara",
  "Toyota 4runner",
  "Toyota Furtuner",
  "Toyota Carina",
  "Toyota Crown",
  "Toyota Corolla",
  "Toyota Corolla GLI-automatic-1800cc",
  "Toyota Corolla XLI-automatic-1800cc",
  "Toyota Corolla GLI-manual-1800cc",
  "Toyota Corolla XLI-manual-1800cc",
  "Toyota Corolla GLI-2000cc",
  "Toyota Corolla SE-1600cc",
  "Toyota Corolla XLI-2000cc",
  "Toyota Corona",
  "Toyota Cressida",
  "Toyota Camry",
  "Toyota Camry Aurion",
  "Toyota Camry manual",
  "Toyota Camry Grand-4 cylinder",
  "Toyota Camry Grand-6 cylinder",
  "Toyota Camry GL",
  "Toyota Camry GLX",
  "Toyota Camry LE",
  "Toyota Camry hybrid-LE",
  "Toyota Camry SE",
  "Toyota Camry hybrid-XLE",
  "Toyota Landcruiser 2door",
  "Toyota Landcruiser 2door 2F",
  "Toyota Landcruiser 2door 3F",
  "Toyota Landcruiser 4door",
  "Toyota Landcruiser 4door 4000cc",
  "Toyota Landcruiser 4door 4500cc",
  "Toyota Landcruiser 4door 4700cc",
  "Toyota Landcruiser 4door 5700cc",
  "Toyota Hilux single cabin",
  "Toyota Hilux double cabin",
  "Toyota Hilux double cabin automatic",
  "Toyota Hilux double cabin high",
  "Toyota Hilux double cabin high automatic",
  "Toyota Hilux double cabin high manual",
  "Toyota Hilux double cabin manual",
  "Toyota Yaris Sedan",
  "Toyota Yaris Sedan 1300cc",
  "Toyota Yaris Sedan 1500cc",
  "Toyota Yaris Hatchback",
  "Toyota Yaris Hatchback 1300cc",
  "Toyota Yaris Hatchback 1500cc",
  "Toyota C-HR",
  "Toyota C-HR Petrol Singledifferential",
  "Toyota C-HR Petrol doubledifferential",
  "Toyota C-HR hybrid",
  "Toyota GT86",
  "Toyota GT86 automatic",
  "Toyota GT86 manual",
  "Tiba",
  "Tiba Sedan",
  "Tiba Sedan Plus",
  "Tiba Sedan EX",
  "Tiba Sedan EX Bi-fuel",
  "Tiba Sedan SL",
  "Tiba Sedan LX Bi-fuel",
  "Tiba Sedan SX",
  "Tiba Sedan SX Bi-fuel",
  "Tiba Hatchback",
  "Tiba Hatchback Plus",
  "Tiba Hatchback EX",
  "Tiba Hatchback SX",
  "JAC",
  "JAC J3 Sedan",
  "JAC J3 Hatchback",
  "JAC J4",
  "JAC J5",
  "JAC J5 automatic-1500cc",
  "JAC J5 manual-1500cc",
  "JAC S3",
  "JAC S3 automatic",
  "JAC S5",
  "JAC S5 automatic",
  "JAC S5 manual",
  "JAC S5 New Face",
  "Jaguar",
  "Jaguar XJ",
  "Joylong",
  "JMC",
  "JMC S350",
  "GAC Gonow",
  "GAC Gonow G5",
  "GAC Gonow GA3S",
  "GAC Gonow GS5",
  "Jeep",
  "Jeep Ahoo",
  "Jeep Cherokee",
  "Jeep Wrangler",
  "Jeep Renegade",
  "Jeep Shahbaz",
  "Jeep Sahra",
  "Jeep Mute",
  "Jeep Wagoneer",
  "Jeep KM",
  "Geely",
  "Geely Emgrand 7",
  "Geely Emgrand 7 automatic",
  "Geely Emgrand 7 manual",
  "Geely Emgrand 7_RV",
  "Geely Emgrand 7_RV automatic",
  "Geely Emgrand 7_RV manual",
  "Geely Emgrand X7",
  "Geely GC6",
  "Geely GC6 excellent",
  "Geely GC6 elite",
  "Changan",
  "Changan CS35",
  "Changan CS35-ir",
  "Changan EADO",
  "Chery",
  "Chery Arrizo 5",
  "Chery Arrizo 5 automatic-excellent",
  "Chery Arrizo 5 automati-luxury",
  "Chery Arrizo 5 manual-luxury",
  "Chery Arrizo 5IE New",
  "Chery Arrizo 5IE New Turbo",
  "Chery Arrizo 5TE",
  "Chery Arrizo 5TE turbo-excellent",
  "Chery Arrizo 6",
  "Chery Arrizo 6 excellent",
  "Chery Tiggo 5",
  "Chery Tiggo 5 excellent",
  "Chery Tiggo 5 luxury",
  "Chery Tiggo 5 luxury-sport",
  "Chery Tiggo 5 IE",
  "Chery Tiggo 5 IL",
  "Chery Tiggo 5 TE",
  "Chery Tiggo 7",
  "Chery Tiggo 7 excellent",
  "Chery Tiggo 7 IE",
  "Chery Viana A15",
  "Datsun",
  "Domy",
  "Domy X7",
  "Dongfeng",
  "Dongfeng H30",
  "Dongfeng S30",
  "Dayun",
  "Dayun Y5",
  "Daihatsu",
  "Delica",
  "Dena",
  "Dena plus",
  "Dena plus Manual 6 Turbo",
  "Dena plus 1700cc Automatic",
  "Dena plus Turbo 1",
  "Dena plus Manual 1",
  "Dena plus 1700cc-turbo",
  "Dena plus 1700cc Manual",
  "Dena basic",
  "Dena basic 1700cc",
  "Dena basic 2",
  "Dodge",
  "Dodge Coronet",
  "Daewoo",
  "Daewoo Espero",
  "Daewoo Espero automatic",
  "Daewoo Espero manual",
  "Daewoo Racer",
  "Daewoo Racer hatchback",
  "Daewoo Racer GTE",
  "Daewoo Racer GTI",
  "Daewoo Cielo",
  "Daewoo Cielo sedan",
  "Daewoo Cielo hatchback",
  "Daewoo Matiz",
  "DS",
  "DS 3",
  "DS 5",
  "DS 5LS",
  "DS 6",
  "DS Crossback-4",
  "DS crossback-7",
  "DS crossback-7 opera",
  "DS crossback-7 rivoli",
  "Dignity",
  "Deer",
  "Runna",
  "Runna Plus",
  "Runna Plus P",
  "Runna EL",
  "Runna LX",
  "Rayen",
  "Rayen V5",
  "Rayen V5 automatic",
  "Rayen V5 manual",
  "Renault",
  "Renault 21",
  "Renault 5",
  "Renault 5-ir",
  "Renault Scala",
  "Renault Scala 1600cc",
  "Renault Scala convertible",
  "Renault Scala E2",
  "Renault Scala E4",
  "Renault Pars Tondar",
  "Renault Pars Tondar manual",
  "Renault PK",
  "Renault Talisman",
  "Renault Talisman E2",
  "Renault Talisman E3",
  "Renault Tondar 90",
  "Renault Tondar 90 automatic",
  "Renault Tondar 90 station",
  "Renault Tondar 90 plus",
  "Renault Tondar 90 plus automatic",
  "Renault Tondar 90 plus manual",
  "Renault Tondar 90 E0-petrol",
  "Renault Tondar 90 E0-Bi-fuel",
  "Renault Tondar 90 E1-petrol",
  "Renault Tondar 90 E1-Bi-fuel",
  "Renault Tondar 90 E2-petrol",
  "Renault Tondar 90 E2-Bi-fuel",
  "Renault Duster",
  "Renault Duster PE Singledifferential",
  "Renault Duster PE doubledifferential",
  "Renault Duster SE Singledifferential",
  "Renault Duster SE doubledifferential",
  "Renault Sandero",
  "Renault Sandero automatic",
  "Renault Sandero-Stepway",
  "Renault Sandero-Stepway automatic",
  "Renault Sandero-Stepway manual",
  "Renault Sandero manual",
  "Renault Sepand",
  "Renault Safrane",
  "Renault Safrane LE-2500cc",
  "Renault Safrane PE-2000cc",
  "Renault Safrane PE-2500cc",
  "Renault Safrane SE-2000cc",
  "Renault Symbol",
  "Renault Symbol LE",
  "Renault Symbol PE",
  "Renault Symbol SE",
  "Renault Fluence",
  "Renault Fluence manual",
  "Renault Fluence E2",
  "Renault Fluence E4",
  "Renault Captur",
  "Renault Koleos",
  "Renault Koleos first generation",
  "Renault Koleos second generation",
  "Renault Laguna",
  "Renault Laguna coupe",
  "Renault Latitude",
  "Renault Megan",
  "Renault Megan 1600cc",
  "Renault Megan 2000cc",
  "Renault Megan convertible",
  "Renault Megan-ir",
  "Renault Megan-ir 2000cc",
  "Renault Megan-ir E1-1600cc",
  "Renault Megan-ir E2-1600cc",
  "Renault Megan hatchback",
  "Rollsroyce",
  "Rich",
  "Rigan",
  "Rigan Coupa",
  "Rigan Coupa exclusive",
  "Rigan Coupa royal",
  "Rigan Coupa flagship",
  "Zamyad",
  "Zamyad Padra",
  "Zamyad Padra Plus",
  "Zamyad Dorka",
  "Zamyad Shooka",
  "Zamyad Z 24",
  "Zamyad Z 24 Petrol",
  "Zamyad Z 24 Petrol Optional",
  "Zamyad Z 24 Bi-fuel",
  "Zamyad Z 24 Bi-fuel Optional",
  "Zamyad Z 24 diesel",
  "Zotye",
  "Zotye Z300-im",
  "SsangYong",
  "SsangYong Actyon",
  "SsangYong Tivoli",
  "SsangYong Tivoli armour",
  "SsangYong Tivoli sport",
  "SsangYong Tivoli elite",
  "SsangYong Tivoli-IR",
  "SsangYong Tivoli-IR Special",
  "SsangYong Tivoli-IR Solar",
  "SsangYong Tivoli-IR Fighter",
  "SsangYong Tivoli-IR Armour",
  "SsangYong Chairman",
  "SsangYong Rexton",
  "SsangYong Rexton basic",
  "SsangYong Rexton-ir",
  "SsangYong Rexton-ir Emperor",
  "SsangYong Rexton-ir G4",
  "SsangYong Rexton G4",
  "SsangYong Rodius",
  "SsangYong Kyron",
  "SsangYong Korando",
  "SsangYong Korando 2300cc",
  "SsangYong Korando 3200cc",
  "SsangYong Musso",
  "SsangYong Musso E23M1",
  "SsangYong Musso E32M3",
  "SsangYong Musso E32M1",
  "SsangYong new actyon",
  "SsangYong new actyon prestige",
  "SsangYong new actyon comfort",
  "SsangYong new actyon luxury",
  "SsangYong new-korando",
  "SsangYong new-korando Optimum",
  "SsangYong new-korando Premium",
  "SsangYong new-korando Premium Plus",
  "Saina",
  "Saina automatic",
  "Saina manual",
  "Saina manual Plus",
  "Saina manual EX",
  "Saina manual G",
  "Saina manual S",
  "Saina manual SX",
  "Seat",
  "Seat Leon",
  "Samand",
  "Samand Sarir",
  "Samand Soren",
  "Samand Soren Plus",
  "Samand Soren basic",
  "Samand Soren ELX",
  "Samand Soren ELX turbo",
  "Samand EL",
  "Samand EL petrol",
  "Samand EL Bi-fuel",
  "Samand LX",
  "Samand LX basic",
  "Samand LX EF7-petrol",
  "Samand LX EF7",
  "Samand SE",
  "Samand X7",
  "Samand X7 petrol",
  "Samand X7 Bi-fuel",
  "Datsun Car",
  "Soueast",
  "Soueast DX-3",
  "Subaru",
  "Subaru Forester",
  "Subaru Legacy",
  "Subaru Way Wave",
  "Subaru X7",
  "Suzuki",
  "Suzuki Kizashi",
  "Suzuki Kizashi automatic",
  "Suzuki Kizashi manual",
  "Suzuki Grand-Vitara",
  "Suzuki Grand-Vitara automatic-2000cc",
  "Suzuki Grand-Vitara manual-2000cc",
  "Suzuki Grand-Vitara-ir",
  "Suzuki Grand-Vitara-ir automatic-2000cc",
  "Suzuki Grand-Vitara-ir automatic-2400cc",
  "Suzuki Grand-Vitara-ir manual-2000cc",
  "Suzuki Grand-Vitara-ir manual-2400cc",
  "Citroen",
  "Citroen Xantia",
  "Citroen Xantia 1800cc",
  "Citroen Xantia2",
  "Citroen Xantia 2000cc",
  "Citroen Jian",
  "Citroen C3",
  "Citroen C3 wo-warmer",
  "Citroen C3 wt-warmer",
  "Citroen C5",
  "Citroen New C5",
  "Sinad",
  "Shahin",
  "Shahin G",
  "Chevrolet",
  "Chevrolet Impala",
  "Chevrolet Bel Air",
  "Chevrolet Blazer",
  "Chevrolet Royal-ir",
  "Chevrolet Suburban",
  "Chevrolet Fleetmaster",
  "Chevrolet Caprice",
  "Chevrolet Camaro",
  "Chevrolet Monte Carlo",
  "Chevrolet Nova",
  "Chevrolet Nova-ir",
  "Farda",
  "Farda 511",
  "Farda Sx5",
  "Farda Sx6",
  "Farda T5",
  "Foton",
  "Foton Sauvana",
  "Ford",
  "Ford Taurus",
  "Ford Mustang",
  "Ford F150",
  "Volkswagen",
  "Volkswagen Beetle",
  "Volkswagen Beetle convertible",
  "Volkswagen Beetle Coupe",
  "Volkswagen Passat",
  "Volkswagen Tiguan",
  "Volkswagen Caddy",
  "Volkswagen Gol",
  "Volkswagen Golf",
  "Volkswagen Golf basic",
  "Volkswagen Golf GTI",
  "Fownix",
  "Fownix Arrizo 6 pro",
  "Fownix Tiggo 7 pro",
  "Fownix Tiggo 8 pro",
  "Fiat",
  "Fiat 500",
  "Fiat Siena",
  "Fidelity",
  "Fidelity Prime",
  "Fidelity Prime 5seater",
  "Fidelity Prime 7seater",
  "Capra",
  "Capra Capra 2",
  "Capra Single-cabin",
  "Capra Single-cabin singledifferential",
  "Capra Double Cabin",
  "Capra Double Cabin singledifferential",
  "Capra Double Cabin doubledifferential",
  "Chrysler",
  "Quick",
  "Quick Automatic",
  "Quick automatic-full",
  "Quick automatic-full plus",
  "Quick Automatic S",
  "Quick manual",
  "Quick manual basic",
  "Quick manual G",
  "Quick manual R",
  "Quick manual R Plus",
  "Quick manual S",
  "Kia",
  "Kia Optima",
  "Kia Optima 2400cc",
  "Kia Optima 2700cc",
  "Kia Optima-hybrid",
  "Kia Optima GT Line 2400cc",
  "Kia Opirus",
  "Kia Sportage",
  "Kia Sportage 2000cc turbo",
  "Kia Sportage 2400cc",
  "Kia Sportage 2700cc",
  "Kia Sportage GT Line-2400cc",
  "Kia Picanto",
  "Kia Rio",
  "Kia Rio sedan",
  "Kia Rio-ir",
  "Kia Rio-ir automatic",
  "Kia Rio-ir manual",
  "Kia Rio hatchback",
  "Kia Cerato",
  "Kia Cerato automatic-1600cc",
  "Kia Cerato automatic-2000cc",
  "Kia Cerato Coupe",
  "Kia Cerato Coupe 1600cc",
  "Kia Cerato Coupe 2000cc",
  "Kia Cerato-ir",
  "Kia Cerato-ir automatic-2000cc",
  "Kia Cerato-ir optional-automatic-2000cc",
  "Kia Cerato-ir manual-1600cc",
  "Kia Cerato-ir manual-optional-1600cc",
  "Kia Sorento",
  "Kia Sorento first generation-(2002-2009)",
  "Kia Sorento second generation",
  "Kia Sorento third generation-(2016-present)",
  "Kia Sorento GT Line-third generation",
  "Kia soul",
  "Kia cadenza",
  "Kia carnival",
  "Kia carens",
  "Kia mohave",
  "Kia mohave 6 cylinder",
  "Kia mohave 8 cylinder",
  "KMC",
  "KMC J7",
  "KMC K7",
  "KMC T8",
  "Great-Wall",
  "Great-Wall Pickup Wingle 5-single cabin",
  "Great-Wall Pickup Wingle 5-single cabin singledifferential",
  "Great-Wall Pickup Wingle 5-single cabin doubledifferential",
  "Great-Wall Pickup Wingle 5-double cabin",
  "Great-Wall Pickup Wingle 5-double cabin singledifferential",
  "Great-Wall Pickup Wingle 5-double cabin doubledifferential",
  "Great-Wall C30",
  "Great-Wall C30 automatic",
  "Great-Wall C30 manual",
  "Lada",
  "Lada Niva",
  "Lamari",
  "Lamari Eama",
  "Lamborghini",
  "Lexus",
  "Lexus CT",
  "Lexus CT 200-hybrid",
  "Lexus CT 200-hybrid-F-sport",
  "Lexus ES",
  "Lexus ES 250",
  "Lexus ES 350",
  "Lexus GS",
  "Lexus GS 250",
  "Lexus GS 250-F-sport",
  "Lexus GS 430",
  "Lexus GS 460",
  "Lexus IS",
  "Lexus IS 250",
  "Lexus IS 250-F-sport",
  "Lexus IS 300",
  "Lexus IS convertible",
  "Lexus IS convertible 300",
  "Lexus LS",
  "Lexus LS 460L",
  "Lexus LX",
  "Lexus LX 570",
  "Lexus NX 200t",
  "Lexus NX 200t premium",
  "Lexus NX 200t paltinum",
  "Lexus NX 200t F",
  "Lexus NX 300 H",
  "Lexus NX 300 H 300-hybrid",
  "Lexus NX 300 H 300-hybrid-F-sport",
  "Lexus RX",
  "Lexus RX 200t-luxury",
  "Lexus RX 200T-F-sport",
  "Lexus RX 350",
  "Lexus RX 350-F-sport",
  "Land Rover",
  "Land Rover Discovery",
  "Land Rover Defender",
  "Land Rover Range Rover",
  "Land Rover Range Rover-Evoque",
  "Land Rover ir",
  "Land Rover Freelander",
  "Landmark",
  "Landmark V7",
  "Lotus",
  "Lotus Elise",
  "Lotus Elise 220 cup",
  "Lotus Elise S",
  "Luxgen",
  "Luxgen U6",
  "Lifan",
  "Lifan 520",
  "Lifan 520i",
  "Lifan 620",
  "Lifan 620 1600cc",
  "Lifan 620 1800cc",
  "Lifan 820",
  "Lifan X50",
  "Lifan X50 automatic",
  "Lifan X50 manual",
  "Lifan X60",
  "Lifan X60 automatic",
  "Lifan X60 manual",
  "Lifan X70",
  "Maserati",
  "Maserati Quattroporte",
  "Maserati Quattroporte basic",
  "Maserati Quattroporte GTS",
  "Maserati Quattroporte S",
  "Maserati Granturismo",
  "Maserati Granturismo basic",
  "Maserati Granturismo MC",
  "Maserati Granturismo S",
  "Maserati Grancabrio",
  "Maserati Grancabrio basic",
  "Maserati Grancabrio MC",
  "Maserati Grancabrio S",
  "Maserati Ghibli",
  "Mazda",
  "Mazda 2-ir",
  "Mazda 2-ir 2",
  "Mazda 3-ir",
  "Mazda 3-ir 1",
  "Mazda 3-ir 2",
  "Mazda 3-ir 3",
  "Mazda 323",
  "Mazda 323 automatic",
  "Mazda 323 manual",
  "Mazda 323 F",
  "Mazda 3N Sedan-ir",
  "Mazda 3N Sedan-ir 1",
  "Mazda 3N Sedan-ir 2",
  "Mazda 3N Sedan-ir 3",
  "Mazda 3N Sedan-ir 4",
  "Mazda 3N Hatchback-ir",
  "Mazda 3N Hatchback-ir 1",
  "Mazda 3N Hatchback-ir 3",
  "Mazda 6",
  "Maxmotor",
  "Maxmotor Kalut",
  "Maxmotor Kalut manual",
  "Maxus",
  "Mitsubishi",
  "Mitsubishi Outlander",
  "Mitsubishi Outlander 3",
  "Mitsubishi Outlander 4",
  "Mitsubishi Outlander 5",
  "Mitsubishi Outlander PHEV",
  "Mitsubishi Pajero 2 door",
  "Mitsubishi Pajero 2 door 4 cylinder",
  "Mitsubishi Pajero 2 door 6 cylinder",
  "Mitsubishi Pajero 4 door",
  "Mitsubishi Pajero 4 door 4 cylinder",
  "Mitsubishi Pajero 4 door 6 cylinder",
  "Mitsubishi Pajero-ir",
  "Mitsubishi Pajero-ir automatic",
  "Mitsubishi Pajero-ir manual",
  "Mitsubishi Galant",
  "Mitsubishi Lancer",
  "Mitsubishi Lancer 1800cc",
  "Mitsubishi Lancer automatic-1600cc",
  "Mitsubishi Lancer manual-1600cc",
  "Mitsubishi Mirage",
  "Mitsubishi ASX",
  "Mitsubishi ASX 4",
  "Mitsubishi ASX midline",
  "Mitsubishi ASX highline",
  "MINI",
  "MINI Countryman",
  "MINI Countryman S",
  "MINI Clubman",
  "MINI Clubman S",
  "MINI Classic",
  "MINI Cooper S",
  "MINI Cooper S 3 door",
  "MINI Cooper S 5 door",
  "Nissan",
  "Nissan Altima",
  "Nissan X-Trail",
  "Nissan X-Trail automatic",
  "Nissan X-Trail manual",
  "Nissan Patrol 2 door",
  "Nissan Patrol 2 door 4 cylinder",
  "Nissan Patrol 4 door",
  "Nissan Patrol 4 door 4 cylinder",
  "Nissan Patrol 4 door 6 cylinder",
  "Nissan Pathfinder",
  "Nissan Pickup double-cabin petrol",
  "Nissan Pickup double-cabin Bi-fuel",
  "Nissan Teana-ir",
  "Nissan Teana-ir HI",
  "Nissan Teana-ir MID",
  "Nissan Teana-im",
  "Nissan Tiida",
  "Nissan Juke",
  "Nissan Juke sport",
  "Nissan Juke skypack",
  "Nissan Juke platinum",
  "Nissan Roniz",
  "Nissan Sunny",
  "Nissan Seranza",
  "Nissan Qashqai",
  "Nissan Qashqai-ir",
  "Nissan Maxima-ir",
  "Nissan Maxima-ir automatic",
  "Nissan Maxima-ir manual",
  "Nissan Maxima-im",
  "Nissan Murano",
  "Nissan Murano LE",
  "Nissan Murano SE",
  "Nissan Murano SL",
  "Arisan Arisan",
  "Arisan Arisan petrol",
  "Arisan Arisan Bi-fuel",
  "Amico Araz",
  "Amico Araz singledifferential",
  "Amico Araz doubledifferential",
  "Amico Asna",
  "Amico Asna petrol",
  "Amico Asna Bi-fuel",
  "Pride Pickup",
  "Pride Pickup Plus",
  "Pride Pickup 151 Bi-fuel",
  "Pride Pickup 151 SE",
  "Pride Pickup 151 SL",
  "GAC Gonow Pickup",
  "GAC Gonow Pickup Troy",
  "Jeep Pickup",
  "Jeep Pickup Simorgh",
  "Datsun Pickup",
  "Deer Deer",
  "Renault Pickup",
  "Renault Pickup Tondar 90",
  "Subaru Pickup",
  "Chevrolet Pickup",
  "Foton Pickup",
  "Foton Pickup Tunland Petrol doubledifferential",
  "Foton Pickup Tunland diesel doubledifferential",
  "Volkswagen Pickup",
  "Great-Wall Pickup Wingle 3",
  "Toyota Pickup",
  "Toyota Pickup Land Cruiser-Pickup-single cabin 2F",
  "Toyota Pickup Land Cruiser-Pickup-single cabin 3F",
  "Toyota Pickup Land Cruiser-Pickup-Single cabin 4.5F",
  "Toyota Pickup Land Cruiser-Pickup-Double cabin 3F",
  "Toyota Pickup Land Cruiser-Pickup-Double cabin 4.5F",
  "Mazda Pickup",
  "Mazda Pickup 1000",
  "Mazda Pickup 1600",
  "Mazda Pickup injector 2000-single cabin petrol",
  "Mazda Pickup injector 2000-single cabin Bi-fuel",
  "Mazda Pickup injector 2000-double cabin petrol",
  "Mazda Pickup injector 2000-double cabin Bi-fuel",
  "Mazda Pickup 2600",
  "Mazda Pickup Cara-single cabin 1700cc",
  "Mazda Pickup Cara-single cabin 2000cc",
  "Mazda Pickup Cara-double cabin 1700cc",
  "Mazda Pickup Cara-double cabin 2000cc",
  "Mitsubishi Pickup",
  "Nissan Pickup",
  "Nissan Pickup Patrol",
  "Nissan Pickup single-cabin",
  "Hyosow T205 Pickup",
  "Volvo",
  "Volvo C30",
  "Volvo C70",
  "Volvo C70 convertible",
  "Volvo V40",
  "Volvo V40 R-Design",
  "Volvo V40 R-Design-Plus",
  "Volvo XC60",
  "Volvo XC60 R-Design",
  "Volvo XC60 T5",
  "Volvo XC90",
  "Volvo XC90 Inscription",
  "Volvo XC90 Momentum",
  "Volvo XC90 R-Design",
  "IranKhodro Van",
  "IranKhodro Van Ghazal",
  "IranKhodro Van Vana",
  "Iveco Van",
  "Iveco Van A36",
  "Brilliance Van",
  "Brilliance Van H2L",
  "Mercedes-Benz Van",
  "Mercedes-Benz Van Vito",
  "Mercedes-Benz Van MB140",
  "Toyota Van",
  "Toyota Van Previa",
  "Toyota Van Hiace",
  "JAC Van",
  "JAC Van Refine",
  "JAC Van Sunray",
  "Joylong Van",
  "Delica Van",
  "Delica Van Taxi",
  "Delica Van Personal",
  "Dodge Van",
  "Renault Van",
  "Renault Van Traffic",
  "Saipa",
  "Saipa Karvan Saipa",
  "Chevrolet Van",
  "Chevrolet Van Vandura",
  "Faw",
  "Faw Siba",
  "Foton Van",
  "Volkswagen Van",
  "Volkswagen Van Transporter",
  "Volkswagen Van Caddy",
  "Volkswagen Van T2",
  "Volkswagen Van T2 Camper",
  "Volkswagen Van T3",
  "Kia Van",
  "Great-Wall Van",
  "Great-Wall Van 13 Seater",
  "Great-Wall Van 9 Seater",
  "Maxus Van",
  "Mitsubishi Van",
  "Mitsubishi Van Caspian",
  "Narvan",
  "Narvan Taxi",
  "Narvan Personal",
  "Hyundai Van",
  "Hyundai Van H1",
  "Hyundai Van H350",
  "Hafei Lobo",
  "Hafei Lobo Lobo",
  "Hummer",
  "Hummer H2",
  "Haval",
  "Haval H2-ir",
  "Haval H6",
  "Haval H6-ir",
  "Haval H9",
  "Haval M4",
  "Haval M4-ir",
  "Haima",
  "Haima S5",
  "Haima S5 6 AT",
  "Haima S5 AT CVT",
  "Haima S7",
  "Haima S7 automatic-2000cc",
  "Haima S7 Plus",
  "Haima S7 automatic-turbo-1800cc",
  "Hanteng",
  "Hanteng X5-ir",
  "Hanteng X7-ir",
  "Honda",
  "Honda Accord",
  "Honda Accord DX",
  "Honda Accord EX",
  "Honda Accord EXA",
  "Honda Accord EXB",
  "Honda Accord EXL",
  "Honda Accord LXB",
  "Honda Civic",
  "Honda Legend",
  "Honda CR-V",
  "Honda CR-V Touring",
  "Honda CR-V EX-L",
  "Honda CR-X",
  "Hillman",
  "Hyosow",
  "Hyundai",
  "Hyundai Azera Grandeur",
  "Hyundai Azera Grandeur 2400cc",
  "Hyundai Azera Grandeur 3000cc",
  "Hyundai Azera Grandeur 3300cc",
  "Hyundai Avante",
  "Hyundai Avante automatic",
  "Hyundai Avante manual",
  "Hyundai Scoupe",
  "Hyundai Excel",
  "Hyundai Accent",
  "Hyundai Accent blue",
  "Hyundai Accent basic",
  "Hyundai Accent-ir",
  "Hyundai Elantra",
  "Hyundai Elantra 1600cc",
  "Hyundai Elantra 1800cc",
  "Hyundai Elantra 2000cc",
  "Hyundai Elantra-ir",
  "Hyundai Trajet",
  "Hyundai Tucson-ix35",
  "Hyundai Tucson-ix35 2000cc",
  "Hyundai Tucson-ix35 2400cc",
  "Hyundai Tucson-ix35 2700cc",
  "Hyundai Genesis Sedan",
  "Hyundai Genesis Coupe",
  "Hyundai Santafe ix45",
  "Hyundai Santafe ix45 2400cc",
  "Hyundai Santafe ix45 2700cc",
  "Hyundai Santafe ix45 3500cc",
  "Hyundai Centennial",
  "Hyundai Sonata-LF",
  "Hyundai Sonata-LF-hybrid",
  "Hyundai Sonata-LF-hybrid GL",
  "Hyundai Sonata-LF-hybrid GLS",
  "Hyundai Sonata-LF-hybrid GLS-Plus",
  "Hyundai Sonata-NF",
  "Hyundai Sonata-NF NF-3300cc",
  "Hyundai Sonata-NF automatic-2400cc",
  "Hyundai Sonata-NF manual-2400cc",
  "Hyundai Sonata-YF",
  "Hyundai Veracruz-ix55",
  "Hyundai Verna",
  "Hyundai Verna automatic",
  "Hyundai Verna manual",
  "Hyundai Veloster",
  "Hyundai FX Coupe",
  "Hyundai FX Coupe automatic",
  "Hyundai FX Coupe manual",
  "Hyundai i10-ir",
  "Hyundai i20",
  "Hyundai i20-ir",
  "Hyundai i20-ir optional",
  "Hyundai i20-ir basic",
  "Hyundai i30",
  "Hyundai i40",
  "Hyundai i40 Station",
  "Uaz",
  "Uaz Patriot",
  "Uaz Pickup",
  "other",
]
