module.exports.phoneBrands = [
  "acer",
  "acer liquid glow e330",
  "acer liquid gallant e350",
  "acer liquid z110",
  "acer liquid c1",
  "acer liquid e1",
  "acer liquid z2",
  "acer liquid e2",
  "acer liquid s1",
  "acer liquid s2",
  "acer liquid z3",
  "acer liquid e3 duo plus",
  "acer liquid z5",
  "acer liquid e3",
  "acer liquid z4",
  "acer liquid e600",
  "acer liquid e700",
  "acer liquid jade",
  "acer liquid x1",
  "acer liquid z200",
  "acer liquid z500",
  "acer liquid jade s",
  "acer liquid z410",
  "acer liquid z220",
  "acer liquid z520",
  "acer liquid x2",
  "acer liquid jade primo",
  "acer liquid m320",
  "acer liquid m330",
  "acer liquid z320",
  "acer liquid z330",
  "acer liquid z530",
  "acer liquid z530s",
  "acer liquid z630",
  "acer liquid z630s",
  "acer liquid jade 2",
  "acer liquid zest",
  "acer liquid zest plus",
  "acer liquid z6",
  "acer liquid z6 plus",
  "alcatel",
  "alcatel fire s",
  "alcatel ot-992d",
  "alcatel ot-995",
  "alcatel ot-997d",
  "alcatel ot-997",
  "alcatel ot-988 shockwave",
  "alcatel ot-983",
  "alcatel one touch evo 7",
  "alcatel one touch idol",
  "alcatel one touch idol ultra",
  "alcatel one touch scribe hd",
  "alcatel one touch scribe hd-lte",
  "alcatel one touch scribe x",
  "alcatel idol x",
  "alcatel one touch scribe easy",
  "alcatel one touch snap",
  "alcatel one touch star",
  "alcatel idol s",
  "alcatel one touch pixi",
  "alcatel evolve",
  "alcatel fierce",
  "alcatel hero",
  "alcatel idol alpha",
  "alcatel pop c1",
  "alcatel pop c3",
  "alcatel pop c5",
  "alcatel idol x+",
  "alcatel pop 7",
  "alcatel pop c9",
  "alcatel fire c",
  "alcatel fire e",
  "alcatel idol 2 s",
  "alcatel pop s3",
  "alcatel pop s7",
  "alcatel pop s9",
  "alcatel pixi 2",
  "alcatel pop c2",
  "alcatel fierce 2",
  "alcatel pop d1",
  "alcatel pop d3",
  "alcatel pop d5",
  "alcatel flash",
  "alcatel hero 2",
  "alcatel hero 8",
  "alcatel pop 2 (4.5)",
  "alcatel pop 2 (4.5) dual sim",
  "alcatel pop 2 (5)",
  "alcatel pop 2 (5) premium",
  "alcatel pop icon",
  "alcatel evolve 2",
  "alcatel pixi 3 (3.5)",
  "alcatel pixi 3 (3.5) firefox",
  "alcatel pixi 3 (4)",
  "alcatel pop 3 (5)",
  "alcatel orange klif",
  "alcatel pixi 3 (5.5)",
  "alcatel pixi 3 (5.5) lte",
  "alcatel pop astro",
  "alcatel flash plus",
  "alcatel flash 2",
  "alcatel go play",
  "alcatel idol 3c",
  "alcatel pixi first",
  "alcatel pop star",
  "alcatel pop star lte",
  "alcatel pop up",
  "alcatel fierce xl",
  "alcatel x1",
  "alcatel fierce xl (windows)",
  "alcatel idol 4s windows",
  "alcatel pixi 4 (3.5)",
  "alcatel pixi 4 (4)",
  "alcatel pixi 4 (6)",
  "alcatel idol 4s",
  "alcatel pop 3 (5.5)",
  "alcatel pop 4",
  "alcatel pop 4+",
  "alcatel pop 4s",
  "alcatel pop 7 lte",
  "alcatel flash plus 2",
  "alcatel pixi 4 (5)",
  "alcatel pixi 4 (6) 3g",
  "alcatel fierce 4",
  "alcatel pixi 4 plus power",
  "alcatel shine lite",
  "alcatel a3 xl",
  "alcatel a3",
  "alcatel a5 led",
  "alcatel u5",
  "alcatel flash (2017)",
  "alcatel idol 5s (usa)",
  "alcatel pulsemix",
  "alcatel u5 hd",
  "alcatel a7",
  "alcatel a7 xl",
  "alcatel idol 5",
  "alcatel idol 5s",
  "alcatel 3c",
  "alcatel 1x",
  "alcatel 3v",
  "alcatel 5",
  "alcatel 5v",
  "alcatel 7",
  "alcatel 3t 8",
  "alcatel 1x (2019)",
  "alcatel 3088",
  "alcatel 3v (2019)",
  "alcatel 3t 10",
  "alcatel 3x (2019)",
  "alcatel go flip 3",
  "alcatel 3l (2020)",
  "alcatel 3x (2020)",
  "alcatel 1se (2020)",
  "alcatel 3l (2021)",
  "amazon",
  "amazon fire phone",
  "apple",
  "apple iphone 4",
  "apple iphone 4 cdma",
  "apple iphone 4s",
  "apple iphone 5",
  "apple iphone 5c",
  "apple iphone 5s",
  "apple iphone 6",
  "apple iphone 6 plus",
  "apple iphone 6s",
  "apple iphone 6s plus",
  "apple iphone se",
  "apple iphone 7",
  "apple iphone 7 plus",
  "apple iphone 8",
  "apple iphone 8 plus",
  "apple iphone x",
  "apple iphone xr",
  "apple iphone xs",
  "apple iphone xs max",
  "apple iphone 11",
  "apple iphone 11 pro",
  "apple iphone 11 pro max",
  "apple iphone se (2020)",
  "apple ipad 10.2 (2020)",
  "apple ipad air (2020)",
  "apple iphone 12",
  "apple iphone 12 mini",
  "apple iphone 12 pro",
  "apple iphone 12 pro max",
  "apple iphone 13",
  "apple iphone 13 mini",
  "apple iphone 13 pro",
  "apple iphone 13 pro max",
  "archos",
  "archos 40 titanium",
  "archos 45 platinum",
  "archos 45 titanium",
  "archos 50 oxygen",
  "archos 50 platinum",
  "archos 50 titanium",
  "archos 53 platinum",
  "archos 53 titanium",
  "archos 45 helium 4g",
  "archos 50 helium 4g",
  "archos 40b titanium",
  "archos 40c titanium",
  "archos 50c oxygen",
  "archos 64 xenon",
  "archos 50b platinum",
  "archos 50b helium 4g",
  "archos 50 diamond",
  "archos 50d helium 4g",
  "archos diamond plus",
  "archos diamond s",
  "archos 50 cobalt",
  "archos 55 cobalt plus",
  "archos diamond 2 plus",
  "archos 50b cobalt",
  "archos 55b cobalt",
  "archos 50 graphite",
  "archos 50 saphir",
  "archos 55 graphite",
  "archos diamond alpha",
  "archos diamond gamma",
  "archos sense 50x",
  "archos sense 55s",
  "archos diamond alpha +",
  "archos diamond omega",
  "archos saphir 50x",
  "asus",
  "asus zenfone pegasus 3s",
  "asus padfone 2",
  "asus padfone infinity",
  "asus fonepad note fhd6",
  "asus padfone infinity 2",
  "asus padfone mini",
  "asus padfone mini (intel)",
  "asus zenfone 4 (2014)",
  "asus zenfone 5 a500cg (2014)",
  "asus zenfone 6 a600cg (2014)",
  "asus zenfone 6 a601cg (2014)",
  "asus padfone infinity lite",
  "asus padfone s",
  "asus padfone x",
  "asus zenfone 4 a450cg (2014)",
  "asus zenfone 5 a500kl (2014)",
  "asus padfone mini 4g (intel)",
  "asus padfone x mini",
  "asus pegasus",
  "asus zenfone 2 ze551ml",
  "asus zenfone 5 a501cg (2015)",
  "asus zenfone c zc451cg",
  "asus zenfone zoom zx550",
  "asus zenfone 2 ze550ml",
  "asus zenfone selfie zd551kl",
  "asus pegasus 2 plus",
  "asus zenfone 2e",
  "asus zenfone 2 deluxe ze551ml",
  "asus zenfone 2 laser ze601kl",
  "asus zenfone go zc500tg",
  "asus zenfone max zc550kl",
  "asus zenfone zoom zx551ml",
  "asus zenfone go zc451tg",
  "asus zenfone go t500",
  "asus zenfone go zb452kg",
  "asus zenfone go zb551kl",
  "asus zenfone 3 deluxe zs570kl",
  "asus zenfone 3 ultra zu680kl",
  "asus zenfone 3 ze552kl",
  "asus zenfone max zc550kl (2016)",
  "asus zenfone pegasus 3",
  "asus zenfone 3 laser zc551kl",
  "asus zenfone go zb450kl",
  "asus zenfone 3 deluxe 5.5 zs550kl",
  "asus zenfone go zb500kl",
  "asus zenfone 3 max zc553kl",
  "asus zenfone go zb690kg",
  "asus zenfone 3s max zc521tl",
  "asus zenfone 3 zoom ze553kl",
  "asus zenfone ar zs571kl",
  "asus zenfone live zb501kl",
  "asus zenfone go zb552kl",
  "asus zenfone 4 max plus zc554kl",
  "asus zenfone 4 max pro zc554kl",
  "asus zenfone 4 max zc520kl",
  "asus zenfone 4 pro zs551kl",
  "asus zenfone 4 selfie pro zd552kl",
  "asus zenfone 4 selfie zd553kl",
  "asus zenfone 4 ze554kl",
  "asus zenfone 4 selfie zb553kl",
  "asus zenfone 4 selfie lite zb553kl",
  "asus zenfone 5 lite zc600kl",
  "asus zenfone 5 ze620kl",
  "asus zenfone 5z zs620kl",
  "asus zenfone max (m1) zb555kl",
  "asus zenfone max pro (m1) zb601kl/zb602k",
  "asus zenfone live (l1) za550kl",
  "asus rog phone zs600kl",
  "asus zenfone lite (l1) za551kl",
  "asus zenfone max (m1) zb556kl",
  "asus zenfone max pro (m2) zb631kl",
  "asus zenfone max plus (m2) zb634kl",
  "asus zenfone max shot zb634kl",
  "asus zenfone live (l2)",
  "asus zenfone 6 zs630kl",
  "asus rog phone ii zs660kl",
  "asus rog phone 3 strix",
  "asus rog phone 3 zs661ks",
  "asus zenfone 7 pro zs671ks",
  "asus zenfone 7 zs670ks",
  "asus rog phone 5",
  "asus rog phone 5 pro",
  "asus rog phone 5 ultimate",
  "asus zenfone 8",
  "asus zenfone 8 flip",
  "asus smartphone for snapdragon insiders",
  "asus rog phone 5s",
  "asus rog phone 5s pro",
  "blackberry",
  "blackberry a10",
  "blackberry q10",
  "blackberry z10",
  "blackberry q5",
  "blackberry 9720",
  "blackberry z30",
  "blackberry z3",
  "blackberry classic",
  "blackberry passport",
  "blackberry classic non camera",
  "blackberry leap",
  "blackberry priv",
  "blackberry dtek50",
  "blackberry dtek60",
  "blackberry keyone",
  "blackberry aurora",
  "blackberry motion",
  "blackberry key2",
  "blackberry evolve",
  "blackberry evolve x",
  "blackberry key2 le",
  "blu",
  "blu studio 5.3",
  "blu elite 3.8",
  "blu dash 3.5",
  "blu dash 3.2",
  "blu dash 4.0",
  "blu vivo 4.65 hd",
  "blu quattro 4.5",
  "blu quattro 4.5 hd",
  "blu quattro 5.7 hd",
  "blu studio 5.3 ii",
  "blu tank 4.5",
  "blu life one",
  "blu life play",
  "blu life view",
  "blu dash music",
  "blu studio 5.0",
  "blu studio 5.0 s",
  "blu studio 5.3 s",
  "blu amour",
  "blu dash 4.5",
  "blu dash 5.0",
  "blu dash jr",
  "blu dash music 4.0",
  "blu zoey",
  "blu studio 5.5",
  "blu life pro",
  "blu advance 4.0",
  "blu life play x",
  "blu life pure",
  "blu studio 5.0 ii",
  "blu life one m",
  "blu life one x",
  "blu life play s",
  "blu studio 5.0 e",
  "blu studio 5.0 s ii",
  "blu studio 5.5 s",
  "blu vivo 4.8 hd",
  "blu life pure mini",
  "blu neo 3.5",
  "blu neo 4.5",
  "blu studio 5.0 lte",
  "blu studio 6.0 hd",
  "blu life 8",
  "blu vivo iv",
  "blu studio 5.0 c",
  "blu studio 5.0 ce",
  "blu studio 5.0 c hd",
  "blu studio c mini",
  "blu win hd",
  "blu win jr",
  "blu life play mini",
  "blu sport 4.5",
  "blu dash c music",
  "blu dash music jr",
  "blu studio mini lte",
  "blu studio 5.0 hd lte",
  "blu studio 6.0 lte",
  "blu life one (2015)",
  "blu life one xl",
  "blu studio energy",
  "blu studio g",
  "blu studio x",
  "blu studio x plus",
  "blu vivo air",
  "blu selfie",
  "blu win hd lte",
  "blu win jr lte",
  "blu advance 4.0 l",
  "blu life 8 xl",
  "blu studio 5.5c",
  "blu studio c",
  "blu energy x plus",
  "blu life x8",
  "blu studio c 5 + 5",
  "blu studio c 5 + 5 lte",
  "blu vivo selfie",
  "blu studio c super camera",
  "blu studio xl",
  "blu energy x",
  "blu pure xl",
  "blu vivo air lte",
  "blu dash l",
  "blu dash m",
  "blu dash x",
  "blu dash x plus",
  "blu studio energy 2",
  "blu studio g lte",
  "blu dash x lte",
  "blu studio g plus",
  "blu life one x (2016)",
  "blu life xl",
  "blu studio c hd",
  "blu vivo 5",
  "blu vivo xl",
  "blu energy x 2",
  "blu neo x plus",
  "blu studio g hd",
  "blu studio m hd",
  "blu studio one",
  "blu studio one plus",
  "blu dash x plus lte",
  "blu energy x lte",
  "blu life mark",
  "blu neo xl",
  "blu studio 5.5 hd",
  "blu studio x mini",
  "blu advance 4.0 l2",
  "blu dash m2",
  "blu dash x2",
  "blu neo x",
  "blu studio selfie 2",
  "blu studio x8 hd",
  "blu dash l2",
  "blu energy jr",
  "blu r1 hd",
  "blu studio touch",
  "blu dash 4.5 (2016)",
  "blu energy diamond mini",
  "blu energy xl",
  "blu grand 5.5 hd",
  "blu neo x mini",
  "blu diamond m",
  "blu energy diamond",
  "blu energy m",
  "blu neo x lte",
  "blu pure xr",
  "blu studio c 8+8",
  "blu studio c 8+8 lte",
  "blu studio g2",
  "blu studio g hd lte",
  "blu studio m lte",
  "blu life one x2",
  "blu vivo 5r",
  "blu advance 4.0 m",
  "blu dash g",
  "blu dash xl",
  "blu energy x plus 2",
  "blu life max",
  "blu studio g max",
  "blu studio g plus hd",
  "blu studio j5",
  "blu studio max",
  "blu studio xl2",
  "blu vivo 6",
  "blu studio g2 hd",
  "blu advance 4.0 l3",
  "blu dash l3",
  "blu grand energy",
  "blu grand m",
  "blu grand max",
  "blu grand x",
  "blu life one x2 mini",
  "blu tank xtreme 4.0",
  "blu tank xtreme 5.0",
  "blu vivo 5 mini",
  "blu vivo xl2",
  "blu studio selfie lte",
  "blu r1 plus",
  "blu studio j2",
  "blu grand xl",
  "blu grand x lte",
  "blu studio j1",
  "blu studio mega",
  "blu r2",
  "blu r2 lte",
  "blu studio j8",
  "blu studio j8 lte",
  "blu tank xtreme pro",
  "blu grand mini",
  "blu grand xl lte",
  "blu studio g mini",
  "blu studio pro",
  "blu vivo 8",
  "blu s1",
  "blu c5 (2017)",
  "blu grand m2",
  "blu grand m2 lte",
  "blu studio g3",
  "blu c5 lte",
  "blu dash l5 lte",
  "blu grand 5.5 hd ii",
  "blu life one x3",
  "blu r2 plus",
  "blu dash l4",
  "blu dash l4 lte",
  "blu studio view xl",
  "blu studio j8m lte",
  "blu vivo xl3",
  "blu vivo xl3 plus",
  "blu vivo one plus",
  "blu grand m3",
  "blu studio g4",
  "blu c5",
  "blu advance l4",
  "blu grand m2 (2018)",
  "blu studio mega (2018)",
  "blu vivo xl4",
  "blu vivo one plus (2019)",
  "blu c5l",
  "blu studio x8 hd (2019)",
  "blu g9",
  "blu g5",
  "blu g5 plus",
  "blu g6",
  "blu g8",
  "blu vivo xl5",
  "blu g9 pro",
  "blu advance l5",
  "blu bold n1",
  "blu studio mega 2019",
  "blu c5 2019",
  "blu c5 plus",
  "blu c6 2019",
  "blu view 1",
  "blu g60",
  "blu g70",
  "blu studio x9 hd",
  "blu g80",
  "blu g90",
  "blu g90 pro",
  "blu studio x10",
  "blu g50",
  "blu g50 plus",
  "blu c5l 2020",
  "blu g50 mega",
  "blu g61",
  "blu g91",
  "blu studio x10+",
  "blu studio x12",
  "blu g91 pro",
  "cat",
  "cat b100",
  "cat b15",
  "cat b15 q",
  "cat s50",
  "cat s40",
  "cat s30",
  "cat s60",
  "cat s31",
  "cat b35",
  "cat s52",
  "cat s42",
  "cat s62 pro",
  "cat s42 h+",
  "cat s22 flip",
  "energizer",
  "energizer energy 200",
  "energizer energy 240",
  "energizer energy 400",
  "energizer energy 500",
  "energizer energy 100",
  "energizer energy 400 lte",
  "energizer hardcase h500s",
  "energizer power max p490s",
  "energizer energy e10+",
  "energizer energy e11",
  "energizer energy e500s",
  "energizer energy e241s",
  "energizer energy e12",
  "energizer hard case g5",
  "energizer u680s",
  "gigabyte",
  "gigabyte gsmart g1362",
  "gigabyte gsmart gs202",
  "gigabyte gsmart maya m1",
  "gigabyte gsmart rio r1",
  "gigabyte gsmart maya m1 v2",
  "gigabyte gsmart sierra s1",
  "gigabyte gsmart simba sx1",
  "gigabyte gsmart aku a1",
  "gigabyte gsmart tuku t2",
  "gigabyte gsmart alto a2",
  "gigabyte gsmart roma r2",
  "gigabyte gsmart rey r3",
  "gigabyte gsmart saga s3",
  "gigabyte gsmart t4",
  "gigabyte gsmart mika m2",
  "gigabyte gsmart arty a3",
  "gigabyte gsmart t4 (lite edition)",
  "gigabyte gsmart gx2",
  "gigabyte gsmart mika m3",
  "gigabyte gsmart akta a4",
  "gigabyte gsmart guru gx",
  "gigabyte gsmart mika mx",
  "gigabyte gsmart roma rx",
  "gigabyte gsmart classic",
  "gigabyte gsmart classic lite",
  "gigabyte gsmart essence",
  "gigabyte gsmart essence 4",
  "gionee",
  "gionee ctrl v1",
  "gionee ctrl v2",
  "gionee ctrl v3",
  "gionee ctrl v4",
  "gionee dream d1",
  "gionee elife e3",
  "gionee elife e5",
  "gionee elife e6",
  "gionee elife e7",
  "gionee gpad g1",
  "gionee gpad g3",
  "gionee pioneer p1",
  "gionee pioneer p2",
  "gionee pioneer p3",
  "gionee gpad g2",
  "gionee ctrl v4s",
  "gionee ctrl v5",
  "gionee gpad g4",
  "gionee gpad g5",
  "gionee m2",
  "gionee elife s5.5",
  "gionee pioneer p2s",
  "gionee pioneer p4",
  "gionee elife s5.1",
  "gionee ctrl v6l",
  "gionee marathon m3",
  "gionee pioneer p5l",
  "gionee pioneer p6",
  "gionee elife s7",
  "gionee pioneer p4s",
  "gionee elife e8",
  "gionee marathon m5",
  "gionee pioneer p2m",
  "gionee marathon m4",
  "gionee f103",
  "gionee pioneer p3s",
  "gionee s5.1 pro",
  "gionee elife s plus",
  "gionee s6",
  "gionee marathon m5 enjoy",
  "gionee marathon m5 lite",
  "gionee marathon m5 plus",
  "gionee pioneer p5w",
  "gionee marathon m5 mini",
  "gionee s8",
  "gionee p5 mini",
  "gionee w909",
  "gionee s6 pro",
  "gionee m6",
  "gionee m6 plus",
  "gionee s6s",
  "gionee f103 pro",
  "gionee p7 max",
  "gionee s9",
  "gionee m2017",
  "gionee p7",
  "gionee steel 2",
  "gionee f5",
  "gionee a1",
  "gionee a1 plus",
  "gionee m6s plus",
  "gionee s10",
  "gionee s10b",
  "gionee s10c",
  "gionee a1 lite",
  "gionee p8 max",
  "gionee x1",
  "gionee m7",
  "gionee x1s",
  "gionee m7 power",
  "gionee m7 plus",
  "gionee s11",
  "gionee s11 lite",
  "gionee s11s",
  "gionee p15 pro",
  "gionee m15",
  "glx",
  "glx arya",
  "glx c6000",
  "glx e51",
  "glx shahab",
  "glx x",
  "glx zoom me c58",
  "google",
  "google pixel",
  "google pixel xl",
  "google pixel 2",
  "google pixel 2 xl",
  "google pixel 3",
  "google pixel 3 xl",
  "google pixel 3a",
  "google pixel 3a xl",
  "google pixel 4",
  "google pixel 4 xl",
  "google pixel 4a",
  "google pixel 4a 5g",
  "google pixel 5",
  "google pixel 5a 5g",
  "gplus",
  "gplus p10",
  "gplus q10",
  "gplus t10",
  "gplus x10",
  "honor",
  "honor 3c",
  "honor 3x g750",
  "honor 3c 4g",
  "honor 3x pro",
  "honor 6",
  "honor 3c play",
  "honor 4 play",
  "honor 4x",
  "honor holly",
  "honor 6 plus",
  "honor 4c",
  "honor bee",
  "honor 7",
  "honor 5x",
  "honor holly 2 plus",
  "honor 5c",
  "honor 5a",
  "honor 8",
  "honor note 8",
  "honor 6x",
  "honor holly 3",
  "honor magic",
  "honor 8 pro",
  "honor 6a (pro)",
  "honor 9",
  "honor 6c pro",
  "honor 7x",
  "honor 9 lite",
  "honor view 10",
  "honor 7a",
  "honor 10",
  "honor 7c",
  "honor 7s",
  "honor 9n (9i)",
  "honor note 10",
  "honor play",
  "honor 8x",
  "honor 8x max",
  "honor 8c",
  "honor magic 2",
  "honor 10 lite",
  "honor view 20",
  "honor play 8a",
  "honor magic 2 3d",
  "honor 20i",
  "honor 20 lite",
  "honor 8a pro",
  "honor 8s",
  "honor 20",
  "honor 20 pro",
  "honor pad 5 10.1",
  "honor 9x pro",
  "honor 20s",
  "honor play 3",
  "honor play 3e",
  "honor 20 lite (china)",
  "honor 9x",
  "honor view30 pro",
  "honor 30s",
  "honor play 9a",
  "honor 20e",
  "honor 30",
  "honor 30 pro",
  "honor 30 pro+",
  "honor 8a 2020",
  "honor 9a",
  "honor 9c",
  "honor 9s",
  "honor 9x lite",
  "honor play 4t",
  "honor play 4t pro",
  "honor 8s 2020",
  "honor x10 5g",
  "honor play4",
  "honor play4 pro",
  "honor 30 youth",
  "honor pad 6",
  "honor x10 max 5g",
  "honor 30i",
  "honor 10x lite",
  "honor v40 lite",
  "honor 50",
  "honor 50 pro",
  "honor 50 se",
  "honor x20 se",
  "honor magic3",
  "honor magic3 pro",
  "honor magic3 pro+",
  "honor play 5t pro",
  "honor x20",
  "htc",
  "htc a12",
  "htc one (m8i)",
  "htc one m8 prime",
  "htc tiara",
  "htc wildfire r70",
  "htc evo 4g",
  "htc evo 4g+",
  "htc evo shift 4g",
  "htc evo 3d cdma",
  "htc evo view 4g",
  "htc jetstream",
  "htc evo design 4g",
  "htc one x",
  "htc one x at&t",
  "htc one xl",
  "htc evo 4g lte",
  "htc j",
  "htc one xc",
  "htc desire x",
  "htc one sc",
  "htc one st",
  "htc windows phone 8s",
  "htc windows phone 8x",
  "htc one vx",
  "htc one x+",
  "htc desire sv",
  "htc droid dna",
  "htc one sv",
  "htc one sv cdma",
  "htc windows phone 8x cdma",
  "htc butterfly",
  "htc desire 400 dual sim",
  "htc desire u",
  "htc one",
  "htc desire l",
  "htc desire p",
  "htc first",
  "htc desire 600 dual sim",
  "htc 8xt",
  "htc butterfly s",
  "htc desire 200",
  "htc one dual sim",
  "htc desire xc",
  "htc one mini",
  "htc desire 500",
  "htc desire 300",
  "htc desire 601",
  "htc one max",
  "htc desire 501",
  "htc desire 601 dual sim",
  "htc desire 700 dual sim",
  "htc desire 501 dual sim",
  "htc desire 310",
  "htc desire 700",
  "htc desire 610",
  "htc desire 626",
  "htc desire 816",
  "htc one (m8)",
  "htc one (m8) cdma",
  "htc desire 210 dual sim",
  "htc desire 310 dual sim",
  "htc desire 616 dual sim",
  "htc desire 816 dual sim",
  "htc one mini 2",
  "htc desire 516 dual sim",
  "htc one (e8)",
  "htc one (m8) dual sim",
  "htc one remix",
  "htc butterfly 2",
  "htc desire 510",
  "htc one (e8) cdma",
  "htc one (m8) for windows",
  "htc one (m8) for windows (cdma)",
  "htc desire 820",
  "htc desire 820 dual sim",
  "htc desire 612",
  "htc desire 820q dual sim",
  "htc desire eye",
  "htc one (m8 eye)",
  "htc desire 620",
  "htc desire 620g dual sim",
  "htc desire 826 dual sim",
  "htc desire 820s dual sim",
  "htc one e9+",
  "htc one m9",
  "htc desire 326g dual sim",
  "htc desire 626g+",
  "htc one m8s",
  "htc one m9+",
  "htc desire 820g+ dual sim",
  "htc one e9",
  "htc one me",
  "htc desire 526",
  "htc desire 626 (usa)",
  "htc desire 520",
  "htc butterfly 3",
  "htc one a9",
  "htc one m9+ supreme camera",
  "htc one e9s dual sim",
  "htc desire 828 dual sim",
  "htc one m9s",
  "htc one x9",
  "htc desire 530",
  "htc desire 630",
  "htc desire 825",
  "htc 10",
  "htc 10 lifestyle",
  "htc one s9",
  "htc desire 628",
  "htc desire 830",
  "htc one m9 prime camera",
  "htc desire 625",
  "htc desire 728 ultra",
  "htc desire 10 pro",
  "htc one a9s",
  "htc 10 evo",
  "htc desire 650",
  "htc desire 10 compact",
  "htc u play",
  "htc u ultra",
  "htc one x10",
  "htc u11",
  "htc u11+",
  "htc u11 life",
  "htc u11 eyes",
  "htc desire 12",
  "htc desire 12+",
  "htc u12+",
  "htc u12 life",
  "htc exodus 1",
  "htc desire 12s",
  "htc desire 19+",
  "htc u19e",
  "htc wildfire x",
  "htc exodus 1s",
  "htc desire 19s",
  "htc desire 20 pro",
  "htc u20 5g",
  "htc wildfire e2",
  "htc desire 20+",
  "htc desire 21 pro 5g",
  "htc wildfire e3",
  "huawei",
  "huawei ascend g628",
  "huawei g10",
  "huawei mate 30 lite",
  "huawei p8 max",
  "huawei ascend d1 xl u9500e",
  "huawei ascend g312",
  "huawei ascend g330d u8825d",
  "huawei ascend p1 xl u9200e",
  "huawei ascend g330",
  "huawei ascend g600",
  "huawei ascend p1 lte",
  "huawei fusion 2 u8665",
  "huawei summit",
  "huawei ascend g500",
  "huawei ascend d2",
  "huawei ascend g510",
  "huawei ascend g525",
  "huawei ascend g615",
  "huawei ascend g700",
  "huawei ascend mate",
  "huawei ascend w1",
  "huawei ascend g350",
  "huawei ascend g526",
  "huawei ascend p2",
  "huawei ascend y210d",
  "huawei ascend y300",
  "huawei premia 4g m931",
  "huawei ascend p6",
  "huawei g610s",
  "huawei ascend g740",
  "huawei ascend y320",
  "huawei ascend y511",
  "huawei u8687 cronos",
  "huawei ascend g535",
  "huawei ascend mate2 4g",
  "huawei ascend p6 s",
  "huawei y300ii",
  "huawei ascend g6",
  "huawei ascend g6 4g",
  "huawei ascend g730",
  "huawei ascend y530",
  "huawei ascend g630",
  "huawei ascend y330",
  "huawei ascend y600",
  "huawei ascend p7 mini",
  "huawei ascend p7",
  "huawei ascend p7 sapphire edition",
  "huawei ascend g620s",
  "huawei ascend g7",
  "huawei ascend mate7",
  "huawei ascend y550",
  "huawei ascend gx1",
  "huawei ascend mate7 monarch",
  "huawei ascend y221",
  "huawei ascend y520",
  "huawei ascend y540",
  "huawei y360",
  "huawei y635",
  "huawei p8",
  "huawei p8lite",
  "huawei p8lite ale-l04",
  "huawei snapto",
  "huawei y625",
  "huawei y560",
  "huawei g8",
  "huawei y6",
  "huawei mate s",
  "huawei nexus 6p",
  "huawei y6 pro",
  "huawei g7 plus",
  "huawei enjoy 5s",
  "huawei p9 lite",
  "huawei p9 plus",
  "huawei y3ii",
  "huawei y5ii",
  "huawei g9 plus",
  "huawei nova plus",
  "huawei y6ii compact",
  "huawei enjoy 6",
  "huawei mate 9",
  "huawei mate 9 porsche design",
  "huawei mate 9 pro",
  "huawei p8 lite (2017)",
  "huawei p10",
  "huawei p10 lite",
  "huawei p10 plus",
  "huawei nova 2",
  "huawei nova 2 plus",
  "huawei y3 (2017)",
  "huawei y6 (2017)",
  "huawei y7",
  "huawei y7 prime",
  "huawei p9 lite mini",
  "huawei mate 10",
  "huawei mate 10 lite",
  "huawei mate 10 porsche design",
  "huawei mate 10 pro",
  "huawei nova 2s",
  "huawei p smart",
  "huawei mate rs porsche design",
  "huawei p20",
  "huawei p20 lite",
  "huawei p20 pro",
  "huawei y7 (2018)",
  "huawei y7 prime (2018)",
  "huawei y7 pro (2018)",
  "huawei y9 (2018)",
  "huawei y6 (2018)",
  "huawei y6 prime (2018)",
  "huawei y3 (2018)",
  "huawei y5 prime (2018)",
  "huawei nova 3",
  "huawei nova 3i",
  "huawei p smart+ 2019",
  "huawei mate 20 lite",
  "huawei mate 20",
  "huawei mate 20 pro",
  "huawei mate 20 rs porsche design",
  "huawei mate 20 x",
  "huawei y9 (2019)",
  "huawei y max",
  "huawei enjoy 9",
  "huawei nova 4",
  "huawei p smart 2019",
  "huawei y5 lite (2018)",
  "huawei y7 prime (2019)",
  "huawei y7 pro (2019)",
  "huawei mate x",
  "huawei y6 pro (2019)",
  "huawei enjoy 9e",
  "huawei enjoy 9s",
  "huawei nova 4e",
  "huawei p30",
  "huawei p30 lite",
  "huawei p30 pro",
  "huawei y6 (2019)",
  "huawei y7 (2019)",
  "huawei y5 (2019)",
  "huawei mate 20 x (5g)",
  "huawei p smart z",
  "huawei nova 5",
  "huawei nova 5i",
  "huawei nova 5 pro",
  "huawei p20 lite (2019)",
  "huawei nova 5i pro",
  "huawei nova 5t",
  "huawei y9 prime (2019)",
  "huawei enjoy 10 plus",
  "huawei mate 30",
  "huawei mate 30 5g",
  "huawei mate 30 pro",
  "huawei mate 30 pro 5g",
  "huawei mate 30 rs porsche design",
  "huawei mediapad m6 turbo 8.4",
  "huawei enjoy 10",
  "huawei enjoy 10s",
  "huawei nova 5z",
  "huawei y9s",
  "huawei nova 6",
  "huawei nova 6 se",
  "huawei p smart pro 2019",
  "huawei nova 7i",
  "huawei p30 lite new edition",
  "huawei y6s (2019)",
  "huawei mate xs",
  "huawei p40 lite",
  "huawei y7p",
  "huawei p40",
  "huawei p40 pro",
  "huawei p40 pro+",
  "huawei matepad 10.4",
  "huawei nova 7 5g",
  "huawei nova 7 pro 5g",
  "huawei nova 7 se",
  "huawei p smart 2020",
  "huawei enjoy z 5g",
  "huawei matepad t8",
  "huawei p30 pro new edition",
  "huawei p40 lite 5g",
  "huawei y5p",
  "huawei y6p",
  "huawei y8p",
  "huawei y8s",
  "huawei enjoy 20 pro",
  "huawei p smart s",
  "huawei matepad 10.8",
  "huawei enjoy 20 5g",
  "huawei enjoy 20 plus 5g",
  "huawei matepad t 10s",
  "huawei p smart 2021",
  "huawei y9a",
  "huawei mate 30e pro 5g",
  "huawei mate 40",
  "huawei mate 40 pro",
  "huawei mate 40 pro+",
  "huawei nova 7 se 5g youth",
  "huawei y7a",
  "huawei nova 8 se",
  "huawei enjoy 20 se",
  "huawei nova 8 5g",
  "huawei nova 8 pro 5g",
  "huawei mate x2",
  "huawei p40 4g",
  "huawei mate 40e",
  "huawei mate 40e 4g",
  "huawei mate 40 pro 4g",
  "huawei mate x2 4g",
  "huawei nova 8i",
  "huawei nova 8 se youth",
  "huawei p50",
  "huawei p50 pro",
  "huawei nova 9",
  "huawei nova 9 pro",
  "lenovo",
  "lenovo a5860",
  "lenovo vibe z3 pro",
  "lenovo zuk z1 mini",
  "lenovo k800",
  "lenovo p700i",
  "lenovo s560",
  "lenovo a789",
  "lenovo k860",
  "lenovo s880",
  "lenovo a660",
  "lenovo p770",
  "lenovo a369i",
  "lenovo a516",
  "lenovo a706",
  "lenovo a800",
  "lenovo a820",
  "lenovo a830",
  "lenovo k900",
  "lenovo s720",
  "lenovo s890",
  "lenovo s920",
  "lenovo a390",
  "lenovo s820",
  "lenovo p780",
  "lenovo a850",
  "lenovo a269i",
  "lenovo a630",
  "lenovo s5000",
  "lenovo vibe x s960",
  "lenovo vibe z k910",
  "lenovo s650",
  "lenovo s930",
  "lenovo a328",
  "lenovo a536",
  "lenovo a859",
  "lenovo a880",
  "lenovo s750",
  "lenovo s850",
  "lenovo a850+",
  "lenovo a316i",
  "lenovo a526",
  "lenovo a8-50 a5500",
  "lenovo a680",
  "lenovo a889",
  "lenovo s939",
  "lenovo golden warrior a8",
  "lenovo vibe z2 pro",
  "lenovo a606",
  "lenovo s580",
  "lenovo vibe x2",
  "lenovo vibe z2",
  "lenovo a319",
  "lenovo s856",
  "lenovo a916",
  "lenovo s90 sisley",
  "lenovo golden warrior note 8",
  "lenovo k3",
  "lenovo a6000",
  "lenovo a616",
  "lenovo p70",
  "lenovo p90",
  "lenovo s60",
  "lenovo vibe x2 pro",
  "lenovo a5000",
  "lenovo a7000",
  "lenovo k3 note",
  "lenovo vibe shot",
  "lenovo a1900",
  "lenovo a6000 plus",
  "lenovo k80",
  "lenovo a3900",
  "lenovo a2010",
  "lenovo zuk z1",
  "lenovo a1000",
  "lenovo a6010",
  "lenovo a6010 plus",
  "lenovo a7000 plus",
  "lenovo phab",
  "lenovo phab plus",
  "lenovo vibe p1",
  "lenovo vibe p1m",
  "lenovo vibe s1",
  "lenovo a3690",
  "lenovo vibe x3",
  "lenovo vibe x3 c78",
  "lenovo a7000 turbo",
  "lenovo k5 note",
  "lenovo lemon 3",
  "lenovo vibe s1 lite",
  "lenovo vibe k5",
  "lenovo vibe k5 plus",
  "lenovo vibe p1 turbo",
  "lenovo zuk z2 pro",
  "lenovo vibe c",
  "lenovo zuk z2",
  "lenovo phab2",
  "lenovo phab2 plus",
  "lenovo phab2 pro",
  "lenovo c2",
  "lenovo vibe a",
  "lenovo a6600",
  "lenovo a6600 plus",
  "lenovo a plus",
  "lenovo c2 power",
  "lenovo k6",
  "lenovo k6 note",
  "lenovo k6 power",
  "lenovo p2",
  "lenovo b",
  "lenovo zuk edge",
  "lenovo k8 note",
  "lenovo k8 plus",
  "lenovo k320t",
  "lenovo k5",
  "lenovo k5 play",
  "lenovo s5",
  "lenovo a5",
  "lenovo k5 note (2018)",
  "lenovo z5",
  "lenovo k5 pro",
  "lenovo k9",
  "lenovo s5 pro",
  "lenovo z5 pro",
  "lenovo s5 pro gt",
  "lenovo z5 pro gt",
  "lenovo z5s",
  "lenovo k6 enjoy",
  "lenovo z6 pro",
  "lenovo z6 youth",
  "lenovo z6 pro 5g",
  "lenovo z6",
  "lenovo a6 note",
  "lenovo k10 note",
  "lenovo k10 plus",
  "lenovo legion duel",
  "lenovo legion pro",
  "lenovo legion 2 pro",
  "lenovo legion duel 2",
  "lenovo k13 note",
  "lenovo k13",
  "lg",
  "lg g4 pro",
  "lg optimus l5 ii",
  "lg optimus vu ii",
  "lg w11",
  "lg t385",
  "lg motion 4g ms770",
  "lg optimus g e975",
  "lg optimus l5 dual e615",
  "lg optimus l9 p760",
  "lg optimus vu p895",
  "lg escape p870",
  "lg intuition vs950",
  "lg optimus g e970",
  "lg splendor us730",
  "lg mach ls860",
  "lg nexus 4 e960",
  "lg optimus l9 p769",
  "lg spectrum ii 4g vs930",
  "lg optimus f7",
  "lg optimus g pro e985",
  "lg optimus l1 ii e410",
  "lg optimus l3 ii dual e435",
  "lg optimus l3 ii e430",
  "lg optimus l7 ii dual p715",
  "lg optimus l7 ii p710",
  "lg lucid2 vs870",
  "lg optimus gj e975w",
  "lg optimus f3",
  "lg optimus l4 ii dual e445",
  "lg optimus l4 ii e440",
  "lg g2",
  "lg optimus l9 ii",
  "lg vu 3 f300l",
  "lg g flex",
  "lg g pro lite",
  "lg g pro lite dual",
  "lg nexus 5",
  "lg optimus l2 ii e435",
  "lg gx f310l",
  "lg 450",
  "lg l45 dual x132",
  "lg l80",
  "lg optimus f3q",
  "lg f70 d315",
  "lg g2 mini",
  "lg g2 mini lte",
  "lg g2 mini lte (tegra)",
  "lg g pro 2",
  "lg l40 d160",
  "lg l40 dual d170",
  "lg l70 d320n",
  "lg l70 dual d325",
  "lg l90 d405",
  "lg l90 dual d410",
  "lg l65 dual d285",
  "lg l80 dual",
  "lg lucid 3 vs876",
  "lg g3",
  "lg l35",
  "lg volt",
  "lg l30",
  "lg l65 d280",
  "lg g3 s",
  "lg g3 s dual",
  "lg l20",
  "lg l50",
  "lg g3 stylus",
  "lg g vista",
  "lg l60",
  "lg l60 dual",
  "lg l bello",
  "lg l fino",
  "lg f60",
  "lg tribute",
  "lg g3 screen",
  "lg g2 lite",
  "lg l prime",
  "lg g flex2",
  "lg joy",
  "lg leon",
  "lg magna",
  "lg spirit",
  "lg aka",
  "lg g4",
  "lg g4c",
  "lg g4 dual",
  "lg g stylo",
  "lg g360",
  "lg bello ii",
  "lg g4 beat",
  "lg tribute 2",
  "lg nexus 5x",
  "lg g vista 2",
  "lg v10",
  "lg ray",
  "lg k4",
  "lg g5",
  "lg k8",
  "lg x cam",
  "lg x screen",
  "lg k5",
  "lg g5 se",
  "lg stylo 2",
  "lg stylus 2 plus",
  "lg x power",
  "lg x style",
  "lg x mach",
  "lg x max",
  "lg x5",
  "lg x skin",
  "lg k3",
  "lg v20",
  "lg u",
  "lg k10 (2017)",
  "lg k20 plus",
  "lg k3 (2017)",
  "lg k4 (2017)",
  "lg k8 (2017)",
  "lg stylus 3",
  "lg g6",
  "lg x power2",
  "lg harmony",
  "lg k7 (2017)",
  "lg x venture",
  "lg q6",
  "lg v30",
  "lg x4+",
  "lg k10 (2018)",
  "lg k8 (2018)",
  "lg v30s thinq",
  "lg zone 4",
  "lg g7 thinq",
  "lg k30",
  "lg q7",
  "lg v35 thinq",
  "lg q stylo 4",
  "lg q stylus",
  "lg k11 plus",
  "lg x power 3",
  "lg g7 fit",
  "lg g7 one",
  "lg q8 (2018)",
  "lg v40 thinq",
  "lg q9",
  "lg tribute empire",
  "lg g8s thinq",
  "lg g8 thinq",
  "lg k40",
  "lg k50",
  "lg q60",
  "lg v50 thinq 5g",
  "lg w10",
  "lg w30",
  "lg w30 pro",
  "lg k20 (2019)",
  "lg k30 (2019)",
  "lg k40s",
  "lg k50s",
  "lg g8x thinq",
  "lg q70",
  "lg v50s thinq 5g",
  "lg k41s",
  "lg k51s",
  "lg k61",
  "lg v60 thinq 5g",
  "lg v60 thinq 5g uw",
  "lg w10 alpha",
  "lg folder 2",
  "lg q61",
  "lg velvet 5g",
  "lg velvet",
  "lg k31",
  "lg q92 5g",
  "lg k22",
  "lg k42",
  "lg k52",
  "lg k62",
  "lg k71",
  "lg k92 5g",
  "lg q31",
  "lg q52",
  "lg wing 5g",
  "lg w31",
  "lg w31+",
  "lg w41",
  "lg w41+",
  "lg w41 pro",
  "meizu",
  "meizu pro 5 mini",
  "meizu mx2",
  "meizu mx4",
  "meizu mx4 pro",
  "meizu m1 note",
  "meizu m1",
  "meizu m2 note",
  "meizu mx5",
  "meizu m2",
  "meizu pro 5",
  "meizu m1 metal",
  "meizu m3",
  "meizu m3 note",
  "meizu mx5e",
  "meizu pro 6",
  "meizu m3s",
  "meizu mx6",
  "meizu m3e",
  "meizu u10",
  "meizu u20",
  "meizu m3 max",
  "meizu m5",
  "meizu m3x",
  "meizu pro 6 plus",
  "meizu pro 6s",
  "meizu m5 note",
  "meizu m5s",
  "meizu e2",
  "meizu m5c",
  "meizu pro 7",
  "meizu pro 7 plus",
  "meizu m6 note",
  "meizu m6",
  "meizu m6s",
  "meizu e3",
  "meizu m6t",
  "meizu m8c",
  "meizu 16",
  "meizu 16 plus",
  "meizu 16x",
  "meizu v8",
  "meizu v8 pro",
  "meizu x8",
  "meizu note 8",
  "meizu c9",
  "meizu c9 pro",
  "meizu note 9",
  "meizu 16s",
  "meizu 16xs",
  "meizu 16s pro",
  "meizu m10",
  "meizu 16t",
  "meizu 17",
  "meizu 17 pro",
  "meizu 18s",
  "meizu 18s pro",
  "meizu 18x",
  "micromax",
  "micromax vdeo 3",
  "microsoft",
  "microsoft lumia 1030",
  "microsoft lumia 1330",
  "microsoft lumia 850",
  "microsoft lumia 535",
  "microsoft lumia 535 dual sim",
  "microsoft lumia 435",
  "microsoft lumia 435 dual sim",
  "microsoft lumia 532",
  "microsoft lumia 532 dual sim",
  "microsoft lumia 430 dual sim",
  "microsoft lumia 640 lte",
  "microsoft lumia 640 xl",
  "microsoft lumia 540 dual sim",
  "microsoft lumia 550",
  "microsoft lumia 950",
  "microsoft lumia 950 dual sim",
  "microsoft lumia 950 xl",
  "microsoft lumia 950 xl dual sim",
  "microsoft lumia 650",
  "microsoft surface duo",
  "microsoft surface duo 2",
  "motorola",
  "motorola moto g60",
  "motorola moto x5",
  "motorola moto z4 force",
  "motorola moto z4 play",
  "motorola p40",
  "motorola droid razr xt912",
  "motorola xt319",
  "motorola droid razr maxx",
  "motorola motosmart me xt303",
  "motorola razr maxx",
  "motorola razr v xt885",
  "motorola droid razr hd",
  "motorola droid razr m",
  "motorola droid razr maxx hd",
  "motorola razr hd xt925",
  "motorola razr i xt890",
  "motorola razr m xt905",
  "motorola electrify m xt905",
  "motorola razr d1",
  "motorola razr d3 xt919",
  "motorola droid maxx",
  "motorola droid mini",
  "motorola droid ultra",
  "motorola moto x",
  "motorola moto g",
  "motorola moto g dual sim",
  "motorola moto e",
  "motorola moto e dual sim",
  "motorola moto g 4g",
  "motorola luge",
  "motorola moto g (2nd gen)",
  "motorola moto g dual sim (2nd gen)",
  "motorola droid turbo",
  "motorola nexus 6",
  "motorola moto maxx",
  "motorola moto g 4g dual sim (2nd gen)",
  "motorola moto g 4g (2nd gen)",
  "motorola moto g (3rd gen)",
  "motorola moto g dual sim (3rd gen)",
  "motorola moto x play",
  "motorola moto x play dual sim",
  "motorola droid maxx 2",
  "motorola moto x force",
  "motorola moto g4",
  "motorola moto g4 play",
  "motorola moto g4 plus",
  "motorola moto z",
  "motorola moto z force",
  "motorola moto e3",
  "motorola moto e3 power",
  "motorola moto g5",
  "motorola moto g5 plus",
  "motorola moto c",
  "motorola moto c plus",
  "motorola moto e4",
  "motorola moto e4 plus",
  "motorola moto e4 plus (usa)",
  "motorola moto e4 (usa)",
  "motorola moto z2 play",
  "motorola moto z2 force",
  "motorola moto g5s",
  "motorola moto g5s plus",
  "motorola moto x4",
  "motorola moto e5",
  "motorola moto e5 play",
  "motorola moto e5 plus",
  "motorola moto g6",
  "motorola moto g6 play",
  "motorola moto g6 plus",
  "motorola moto z3 play",
  "motorola moto e5 play go",
  "motorola moto z3",
  "motorola one (p30 play)",
  "motorola one power (p30 note)",
  "motorola p30",
  "motorola moto g7",
  "motorola moto g7 play",
  "motorola moto g7 plus",
  "motorola moto g7 power",
  "motorola moto z4",
  "motorola moto e6",
  "motorola one action",
  "motorola moto e6 plus",
  "motorola one zoom",
  "motorola moto e6 play",
  "motorola moto g8 play",
  "motorola moto g8 plus",
  "motorola one macro",
  "motorola one hyper",
  "motorola moto g8 power",
  "motorola moto g power",
  "motorola moto e6s (2020)",
  "motorola moto g8",
  "motorola edge",
  "motorola edge+",
  "motorola moto g8 power lite",
  "motorola moto e (2020)",
  "motorola moto g fast",
  "motorola one fusion+",
  "motorola moto g 5g plus",
  "motorola one fusion",
  "motorola one vision plus",
  "motorola moto g9 play",
  "motorola moto e7 plus",
  "motorola moto g9 plus",
  "motorola one 5g",
  "motorola razr 5g",
  "motorola one 5g uw",
  "motorola moto e7",
  "motorola moto g 5g",
  "motorola moto g9 power",
  "motorola edge s",
  "motorola moto g power (2021)",
  "motorola moto g stylus (2021)",
  "motorola one 5g ace",
  "motorola moto e6i",
  "motorola moto e7 power",
  "motorola moto g10",
  "motorola moto g30",
  "motorola moto g100",
  "motorola moto g10 power",
  "motorola moto g50",
  "motorola moto g20",
  "motorola defy (2021)",
  "motorola moto g stylus 5g",
  "motorola edge 20",
  "motorola edge 20 lite",
  "motorola edge 20 pro",
  "motorola edge 20 fusion",
  "motorola moto g50 5g",
  "motorola moto g60s",
  "motorola moto e20",
  "nokia",
  "nokia 5800 xpressmusic",
  "nokia 8.1 plus",
  "nokia 9.3 pureview",
  "nokia n95 8gb",
  "nokia 808 pureview",
  "nokia lumia 820",
  "nokia lumia 920",
  "nokia lumia 510",
  "nokia lumia 810",
  "nokia lumia 822",
  "nokia lumia 505",
  "nokia lumia 620",
  "nokia lumia 520",
  "nokia lumia 720",
  "nokia asha 210",
  "nokia lumia 928",
  "nokia lumia 925",
  "nokia lumia 625",
  "nokia 515",
  "nokia lumia 1320",
  "nokia lumia 1520",
  "nokia lumia 525",
  "nokia lumia icon",
  "nokia x",
  "nokia xl",
  "nokia lumia 630",
  "nokia lumia 630 dual sim",
  "nokia lumia 930",
  "nokia x2 dual sim",
  "nokia lumia 530",
  "nokia lumia 530 dual sim",
  "nokia lumia 730 dual sim",
  "nokia lumia 735",
  "nokia lumia 830",
  "nokia lumia 638",
  "nokia 6",
  "nokia 3",
  "nokia 5",
  "nokia 8",
  "nokia 2",
  "nokia 7",
  "nokia 6.1",
  "nokia 1",
  "nokia 7 plus",
  "nokia 8110 4g",
  "nokia 8 sirocco",
  "nokia 2.1",
  "nokia 3.1",
  "nokia 5.1",
  "nokia 5.1 plus (nokia x5)",
  "nokia 6.1 plus (nokia x6)",
  "nokia 3.1 plus",
  "nokia 7.1",
  "nokia 8.1 (nokia x7)",
  "nokia 1 plus",
  "nokia 3.2",
  "nokia 4.2",
  "nokia 9 pureview",
  "nokia x71",
  "nokia 2.2",
  "nokia 3.1 a",
  "nokia 3.1 c",
  "nokia 220 4g",
  "nokia 2720 flip",
  "nokia 6.2",
  "nokia 7.2",
  "nokia 800 tough",
  "nokia 2.3",
  "nokia c1",
  "nokia 1.3",
  "nokia 5.3",
  "nokia 5310 (2020)",
  "nokia 8.3 5g",
  "nokia c2",
  "nokia c2 tava",
  "nokia c2 tennen",
  "nokia c5 endi",
  "nokia c3",
  "nokia 2.4",
  "nokia 3.4",
  "nokia 225 4g",
  "nokia 6300 4g",
  "nokia 8000 4g",
  "nokia 8 v 5g uw",
  "nokia 5.4",
  "nokia c1 plus",
  "nokia 1.4",
  "nokia c10",
  "nokia c20",
  "nokia g10",
  "nokia x10",
  "nokia x20",
  "nokia 105 4g",
  "nokia 110 4g",
  "nokia c01 plus",
  "nokia c20 plus",
  "nokia c1 2nd edition",
  "nokia c30",
  "nokia xr20",
  "nokia g50",
  "oneplus",
  "oneplus 9e",
  "oneplus 2",
  "oneplus x",
  "oneplus 3",
  "oneplus 3t",
  "oneplus 5",
  "oneplus 5t",
  "oneplus 6",
  "oneplus 6t",
  "oneplus 6t mclaren",
  "oneplus 7",
  "oneplus 7 pro",
  "oneplus 7 pro 5g",
  "oneplus 7t",
  "oneplus 7t pro",
  "oneplus 7t pro 5g mclaren",
  "oneplus 8",
  "oneplus 8 pro",
  "oneplus nord",
  "oneplus 8t",
  "oneplus 8t+ 5g",
  "oneplus nord n100",
  "oneplus nord n10 5g",
  "oneplus 9",
  "oneplus 9 pro",
  "oneplus 9r",
  "oneplus nord ce 5g",
  "oneplus nord n200 5g",
  "oneplus nord 2 5g",
  "oppo",
  "oppo a95 5g",
  "oppo r811 real",
  "oppo r817 real",
  "oppo u705t ulike 2",
  "oppo find 5",
  "oppo r821t find muse",
  "oppo r815t clover",
  "oppo r819",
  "oppo n1",
  "oppo r1 r829t",
  "oppo find 5 mini",
  "oppo neo",
  "oppo find 7",
  "oppo find 7a",
  "oppo r1s",
  "oppo r1001 joy",
  "oppo r2001 yoyo",
  "oppo r3",
  "oppo n1 mini",
  "oppo neo 3",
  "oppo neo 5",
  "oppo n3",
  "oppo r5",
  "oppo mirror 3",
  "oppo r1x",
  "oppo u3",
  "oppo a31 (2015)",
  "oppo joy plus",
  "oppo neo 5s",
  "oppo r7",
  "oppo r7 plus",
  "oppo joy 3",
  "oppo neo 5 (2015)",
  "oppo mirror 5",
  "oppo mirror 5s",
  "oppo r5s",
  "oppo r7 lite",
  "oppo neo 7",
  "oppo a33 (2015)",
  "oppo a53 (2015)",
  "oppo f1",
  "oppo f1 plus",
  "oppo r9 plus",
  "oppo a37",
  "oppo a59",
  "oppo f1s",
  "oppo r9s",
  "oppo r9s plus",
  "oppo a57",
  "oppo a39",
  "oppo f3 plus",
  "oppo a77 (mediatek)",
  "oppo f3",
  "oppo r11",
  "oppo r11 plus",
  "oppo a77",
  "oppo a71",
  "oppo f5",
  "oppo r11s",
  "oppo f5 youth",
  "oppo r11s plus",
  "oppo a83",
  "oppo a71 (2018)",
  "oppo a1",
  "oppo f7",
  "oppo r15",
  "oppo r15 pro",
  "oppo a3",
  "oppo f7 youth",
  "oppo find x",
  "oppo find x lamborghini",
  "oppo a3s",
  "oppo a5 (ax5)",
  "oppo f9 (f9 pro)",
  "oppo r17",
  "oppo rx17 pro",
  "oppo a7x",
  "oppo k1",
  "oppo r15x",
  "oppo a7",
  "oppo rx17 neo",
  "oppo a5s (ax5s)",
  "oppo f11",
  "oppo f11 pro",
  "oppo a1k",
  "oppo a7n",
  "oppo a9",
  "oppo reno 10x zoom",
  "oppo reno 5g",
  "oppo k3",
  "oppo reno2",
  "oppo reno2 f",
  "oppo reno2 z",
  "oppo a5 (2020)",
  "oppo a9 (2020)",
  "oppo reno a",
  "oppo a11",
  "oppo reno ace",
  "oppo a91",
  "oppo reno3 5g",
  "oppo reno3 pro 5g",
  "oppo f15",
  "oppo a31",
  "oppo find x2",
  "oppo find x2 pro",
  "oppo reno3 pro",
  "oppo a12",
  "oppo a12e",
  "oppo a52",
  "oppo a72",
  "oppo a92s",
  "oppo ace2",
  "oppo find x2 lite",
  "oppo find x2 neo",
  "oppo a92",
  "oppo a11k",
  "oppo reno4 5g",
  "oppo reno4 pro 5g",
  "oppo a12s",
  "oppo reno4",
  "oppo a53",
  "oppo k7 5g",
  "oppo a32",
  "oppo a33 (2020)",
  "oppo f17",
  "oppo f17 pro",
  "oppo reno4 se",
  "oppo reno4 z 5g",
  "oppo a15",
  "oppo a53s",
  "oppo a73",
  "oppo a93",
  "oppo a15s",
  "oppo a53 5g",
  "oppo reno5 5g",
  "oppo reno5 pro 5g",
  "oppo reno5 pro+ 5g",
  "oppo a55 5g",
  "oppo a93 5g",
  "oppo a54",
  "oppo a94",
  "oppo f19 pro",
  "oppo f19 pro+ 5g",
  "oppo find x3",
  "oppo find x3 lite",
  "oppo find x3 neo",
  "oppo find x3 pro",
  "oppo reno5 f",
  "oppo a35",
  "oppo a74",
  "oppo a74 5g",
  "oppo a94 5g",
  "oppo f19",
  "oppo reno5 z",
  "oppo reno6 5g",
  "oppo reno6 pro 5g",
  "oppo reno6 pro+ 5g",
  "oppo a16",
  "oppo a93s 5g",
  "oppo reno6",
  "oppo reno6 z",
  "oppo f19s",
  "oppo k9 pro",
  "oppo reno6 pro 5g (snapdragon)",
  "panasonic",
  "panasonic p11",
  "panasonic t11",
  "panasonic t21",
  "panasonic p51",
  "panasonic t31",
  "panasonic p81",
  "panasonic eluga u",
  "panasonic p61",
  "panasonic t41",
  "panasonic eluga a",
  "panasonic p41",
  "panasonic lumix smart camera cm1",
  "panasonic t40",
  "panasonic eluga i",
  "panasonic eluga s",
  "panasonic p55",
  "panasonic eluga u2",
  "panasonic eluga l 4g",
  "panasonic eluga s mini",
  "panasonic eluga z",
  "panasonic eluga i2",
  "panasonic eluga icon",
  "panasonic eluga l2",
  "panasonic t45",
  "panasonic eluga switch",
  "panasonic eluga mark",
  "panasonic eluga turbo",
  "panasonic t50",
  "panasonic eluga a2",
  "panasonic eluga arc",
  "panasonic eluga i3",
  "panasonic eluga i2 (2016)",
  "panasonic eluga note",
  "panasonic eluga arc 2",
  "panasonic p77",
  "panasonic eluga tapp",
  "panasonic eluga mark 2",
  "panasonic p88",
  "panasonic eluga pulse",
  "panasonic eluga pulse x",
  "panasonic eluga ray max",
  "panasonic eluga ray x",
  "panasonic eluga i3 mega",
  "panasonic eluga ray",
  "panasonic p85",
  "panasonic p55 max",
  "panasonic eluga a3",
  "panasonic eluga a3 pro",
  "panasonic eluga i2 activ",
  "panasonic eluga i4",
  "panasonic eluga ray 500",
  "panasonic eluga ray 700",
  "panasonic p9",
  "panasonic p99",
  "panasonic eluga a4",
  "panasonic eluga i5",
  "panasonic p91",
  "panasonic eluga i9",
  "panasonic eluga i7",
  "panasonic eluga ray 550",
  "panasonic p95",
  "panasonic p90",
  "panasonic eluga ray 530",
  "panasonic eluga ray 600",
  "panasonic eluga z1 pro",
  "panasonic p85 nxt",
  "panasonic eluga ray 800",
  "panasonic eluga i7 (2019)",
  "philips",
  "philips w8355",
  "philips t939",
  "philips w8560",
  "philips w8568",
  "philips w8555",
  "philips w7555",
  "philips w9588",
  "philips w8578",
  "philips s308",
  "philips w6610",
  "philips s396",
  "philips s309",
  "philips i908",
  "philips v526",
  "philips i928",
  "philips s337",
  "philips s616",
  "philips v377",
  "philips v787",
  "prestigio",
  "prestigio multiphone 3400 duo",
  "prestigio multiphone 3540 duo",
  "prestigio multiphone 4040 duo",
  "prestigio multiphone 4044 duo",
  "prestigio multiphone 4055 duo",
  "prestigio multiphone 4300 duo",
  "prestigio multiphone 4322 duo",
  "prestigio multiphone 4500 duo",
  "prestigio multiphone 4505 duo",
  "prestigio multiphone 5000 duo",
  "prestigio multiphone 5044 duo",
  "prestigio multiphone 5300 duo",
  "prestigio multiphone 5400 duo",
  "prestigio multiphone 5430 duo",
  "prestigio multiphone 5450 duo",
  "prestigio multiphone 5451 duo",
  "prestigio multiphone 5500 duo",
  "prestigio multiphone 5501 duo",
  "prestigio multiphone 5503 duo",
  "prestigio multiphone 5504 duo",
  "prestigio multiphone 5508 duo",
  "prestigio multiphone 7500",
  "prestigio multiphone 7600 duo",
  "prestigio multiphone 8400 duo",
  "prestigio multiphone 8500 duo",
  "razer",
  "razer phone",
  "razer phone 2",
  "realme",
  "realme 8 5g",
  "realme 7 (global)",
  "realme 7 5g",
  "realme c20",
  "realme narzo 30a",
  "realme narzo 30 pro 5g",
  "realme 8",
  "realme 8 pro",
  "realme c21",
  "realme c25",
  "realme gt 5g",
  "realme gt neo",
  "realme v13 5g",
  "realme x7 pro ultra",
  "realme narzo 30",
  "realme narzo 30 5g",
  "realme q3 pro carnival",
  "realme c11 (2021)",
  "realme c21y",
  "realme c25s",
  "realme gt explorer master",
  "realme gt master",
  "realme 8i",
  "realme 8s 5g",
  "realme c25y",
  "realme gt neo2",
  "realme narzo 50a",
  "realme narzo 50i",
  "realme v11s 5g",
  "samsung",
  "samsung galaxy a91",
  "samsung galaxy c10",
  "samsung galaxy grand 3",
  "samsung galaxy j5 prime (2017)",
  "samsung galaxy m42 5g",
  "samsung galaxy on5 (2016)",
  "samsung galaxy s21",
  "samsung galaxy s6 plus",
  "samsung galaxy s9 active",
  "samsung galaxy z fold 2 5g",
  "samsung i9000 galaxy s",
  "samsung galaxy ace s5830",
  "samsung galaxy mini s5570",
  "samsung m220l galaxy neo",
  "samsung galaxy reverb m950",
  "samsung galaxy ace ii x s7560m",
  "samsung galaxy note ii cdma",
  "samsung galaxy pocket plus s5301",
  "samsung galaxy pop plus s5570i",
  "samsung galaxy note t879",
  "samsung galaxy ace advance s6800",
  "samsung galaxy ace duos s6802",
  "samsung galaxy s duos s7562",
  "samsung ativ s i8750",
  "samsung galaxy camera gc100",
  "samsung galaxy rush m830",
  "samsung galaxy stellar 4g i200",
  "samsung galaxy s relay 4g t699",
  "samsung galaxy victory 4g lte l300",
  "samsung i9305 galaxy s iii",
  "samsung galaxy express i437",
  "samsung galaxy music duos s6012",
  "samsung galaxy music s6010",
  "samsung galaxy rugby pro i547",
  "samsung i8190 galaxy s iii mini",
  "samsung a997 rugby iii",
  "samsung galaxy axiom r830",
  "samsung galaxy discover s730m",
  "samsung galaxy premier i9260",
  "samsung galaxy stratosphere ii i415",
  "samsung galaxy grand i9080",
  "samsung galaxy grand i9082",
  "samsung ativ odyssey i930",
  "samsung e1272",
  "samsung galaxy express i8730",
  "samsung galaxy pop shv-e220",
  "samsung galaxy s ii tv",
  "samsung i9105 galaxy s ii plus",
  "samsung i9506 galaxy s4",
  "samsung s7710 galaxy xcover 2",
  "samsung galaxy fame s6810",
  "samsung galaxy note 8.0",
  "samsung galaxy young s6310",
  "samsung i9502 galaxy s4",
  "samsung galaxy mega 5.8 i9150",
  "samsung galaxy mega 6.3 i9200",
  "samsung galaxy pocket neo s5310",
  "samsung galaxy star s5280",
  "samsung galaxy trend ii duos s7572",
  "samsung galaxy win i8550",
  "samsung galaxy core i8260",
  "samsung galaxy exhibit t599",
  "samsung galaxy s4 cdma",
  "samsung i9190 galaxy s4 mini",
  "samsung galaxy s4 zoom",
  "samsung i9295 galaxy s4 active",
  "samsung galaxy prevail 2",
  "samsung gravity q t289",
  "samsung galaxy note 3",
  "samsung galaxy express 2",
  "samsung galaxy fresh s7390",
  "samsung galaxy light",
  "samsung galaxy round g910s",
  "samsung galaxy star pro s7260",
  "samsung i9230 galaxy golden",
  "samsung galaxy grand 2",
  "samsung galaxy s duos 2 s7582",
  "samsung galaxy core advance",
  "samsung galaxy s4 active lte-a",
  "samsung galaxy win pro g3812",
  "samsung galaxy grand neo",
  "samsung galaxy note 3 neo",
  "samsung galaxy note 3 neo duos",
  "samsung galaxy note 4 (usa)",
  "samsung galaxy note pro 12.2 3g",
  "samsung galaxy core lte",
  "samsung galaxy s5",
  "samsung galaxy s5 (usa)",
  "samsung galaxy star trios s5283",
  "samsung g3812b galaxy s3 slim",
  "samsung galaxy s5 (octa-core)",
  "samsung i8200 galaxy s iii mini ve",
  "samsung ativ se",
  "samsung galaxy ace style",
  "samsung galaxy k zoom",
  "samsung galaxy s5 active",
  "samsung galaxy ace 4",
  "samsung galaxy ace 4 lte g313",
  "samsung galaxy core ii",
  "samsung galaxy core lite lte",
  "samsung galaxy s5 duos",
  "samsung galaxy s5 lte-a g906s",
  "samsung galaxy s5 mini",
  "samsung galaxy s5 sport",
  "samsung galaxy star 2",
  "samsung galaxy young 2",
  "samsung i9301i galaxy s3 neo",
  "samsung galaxy ace nxt",
  "samsung galaxy avant",
  "samsung galaxy star 2 plus",
  "samsung galaxy alpha",
  "samsung galaxy alpha (s801)",
  "samsung galaxy s5 lte-a g901f",
  "samsung galaxy s5 mini duos",
  "samsung galaxy s duos 3",
  "samsung galaxy ace style lte g357",
  "samsung galaxy grand prime",
  "samsung galaxy mega 2",
  "samsung galaxy note 4",
  "samsung galaxy note edge",
  "samsung galaxy v",
  "samsung galaxy a3",
  "samsung galaxy a3 duos",
  "samsung galaxy a5",
  "samsung galaxy a5 duos",
  "samsung galaxy note 4 duos",
  "samsung galaxy s5 plus",
  "samsung galaxy core lte g386w",
  "samsung galaxy core prime",
  "samsung galaxy a7 duos",
  "samsung galaxy e5",
  "samsung galaxy e7",
  "samsung galaxy grand max",
  "samsung galaxy j1",
  "samsung galaxy j1 4g",
  "samsung z1",
  "samsung galaxy s6",
  "samsung galaxy s6 edge",
  "samsung galaxy s6 (usa)",
  "samsung galaxy xcover 3",
  "samsung galaxy j5",
  "samsung galaxy j7",
  "samsung galaxy s4 mini i9195i",
  "samsung galaxy s6 active",
  "samsung galaxy s6 duos",
  "samsung galaxy a8",
  "samsung galaxy folder",
  "samsung galaxy v plus",
  "samsung xcover 550",
  "samsung galaxy a8 duos",
  "samsung galaxy j1 ace",
  "samsung galaxy note5",
  "samsung galaxy note5 duos",
  "samsung galaxy note5 (usa)",
  "samsung galaxy s5 neo",
  "samsung galaxy s6 edge+",
  "samsung galaxy s6 edge+ duos",
  "samsung galaxy j2",
  "samsung galaxy on5",
  "samsung galaxy on7",
  "samsung galaxy view",
  "samsung z3",
  "samsung galaxy a3 (2016)",
  "samsung galaxy a5 (2016)",
  "samsung galaxy a7 (2016)",
  "samsung galaxy j1 (2016)",
  "samsung galaxy j1 nxt",
  "samsung galaxy s7",
  "samsung galaxy s7 edge",
  "samsung galaxy j3 (2016)",
  "samsung galaxy j5 (2016)",
  "samsung galaxy j7 (2016)",
  "samsung galaxy express prime",
  "samsung galaxy xcover 3 g389f",
  "samsung galaxy c5",
  "samsung galaxy c7",
  "samsung galaxy j3 pro",
  "samsung galaxy s7 active",
  "samsung z3 corporate",
  "samsung galaxy j2 (2016)",
  "samsung galaxy j2 pro (2016)",
  "samsung galaxy on5 pro",
  "samsung galaxy on7 pro",
  "samsung galaxy note7",
  "samsung galaxy note7 (usa)",
  "samsung z2",
  "samsung galaxy a8 (2016)",
  "samsung galaxy j5 prime",
  "samsung galaxy j7 prime",
  "samsung galaxy on7 (2016)",
  "samsung galaxy on8",
  "samsung galaxy c9 pro",
  "samsung galaxy grand prime plus",
  "samsung galaxy j2 prime",
  "samsung galaxy j1 mini prime",
  "samsung galaxy a3 (2017)",
  "samsung galaxy a5 (2017)",
  "samsung galaxy a7 (2017)",
  "samsung galaxy c7 pro",
  "samsung galaxy j3 emerge",
  "samsung galaxy c5 pro",
  "samsung galaxy s8",
  "samsung galaxy s8+",
  "samsung galaxy xcover 4",
  "samsung z4",
  "samsung galaxy j3 (2017)",
  "samsung galaxy j5 (2017)",
  "samsung galaxy j7 (2017)",
  "samsung galaxy j7 max",
  "samsung galaxy j7 pro",
  "samsung galaxy folder2",
  "samsung galaxy j7 nxt",
  "samsung galaxy note fe",
  "samsung galaxy note8",
  "samsung galaxy s8 active",
  "samsung galaxy c7 (2017)",
  "samsung galaxy j2 (2017)",
  "samsung galaxy a8 (2018)",
  "samsung galaxy a8+ (2018)",
  "samsung galaxy j2 pro (2018)",
  "samsung galaxy s9",
  "samsung galaxy s9+",
  "samsung galaxy j7 prime 2",
  "samsung galaxy j7 duo",
  "samsung galaxy a6 (2018)",
  "samsung galaxy a6+ (2018)",
  "samsung galaxy j4",
  "samsung galaxy j6",
  "samsung galaxy j8",
  "samsung galaxy s light luxury",
  "samsung galaxy a8 star (a9 star)",
  "samsung galaxy j3 (2018)",
  "samsung galaxy j7 (2018)",
  "samsung galaxy on6",
  "samsung galaxy j2 core",
  "samsung galaxy note9",
  "samsung galaxy a7 (2018)",
  "samsung galaxy j4+",
  "samsung galaxy j6+",
  "samsung galaxy a6s",
  "samsung galaxy a9 (2018)",
  "samsung galaxy j4 core",
  "samsung galaxy a8s",
  "samsung galaxy m10",
  "samsung galaxy m20",
  "samsung galaxy a10",
  "samsung galaxy a30",
  "samsung galaxy a50",
  "samsung galaxy fold",
  "samsung galaxy fold 5g",
  "samsung galaxy m30",
  "samsung galaxy s10",
  "samsung galaxy s10+",
  "samsung galaxy s10 5g",
  "samsung galaxy s10e",
  "samsung galaxy a20",
  "samsung galaxy a40",
  "samsung galaxy a70",
  "samsung galaxy a20e",
  "samsung galaxy a2 core",
  "samsung galaxy a60",
  "samsung galaxy a80",
  "samsung galaxy view2",
  "samsung galaxy m40",
  "samsung galaxy xcover 4s",
  "samsung galaxy a10e",
  "samsung galaxy a10s",
  "samsung galaxy a30s",
  "samsung galaxy a50s",
  "samsung galaxy note10",
  "samsung galaxy note10+",
  "samsung galaxy note10 5g",
  "samsung galaxy note10+ 5g",
  "samsung galaxy a20s",
  "samsung galaxy a70s",
  "samsung galaxy a90 5g",
  "samsung galaxy m10s",
  "samsung galaxy m30s",
  "samsung galaxy xcover fieldpro",
  "samsung galaxy a01",
  "samsung galaxy a51",
  "samsung galaxy a71",
  "samsung galaxy note10 lite",
  "samsung galaxy s10 lite",
  "samsung galaxy xcover pro",
  "samsung galaxy m31",
  "samsung galaxy s20",
  "samsung galaxy s20+",
  "samsung galaxy s20 5g",
  "samsung galaxy s20+ 5g",
  "samsung galaxy s20 ultra",
  "samsung galaxy s20 ultra 5g",
  "samsung galaxy z flip",
  "samsung galaxy a11",
  "samsung galaxy a31",
  "samsung galaxy a41",
  "samsung galaxy m11",
  "samsung galaxy m21",
  "samsung galaxy a21",
  "samsung galaxy a51 5g",
  "samsung galaxy j2 core (2020)",
  "samsung galaxy a21s",
  "samsung galaxy m01",
  "samsung galaxy a01 core",
  "samsung galaxy m01 core",
  "samsung galaxy m01s",
  "samsung galaxy m31s",
  "samsung galaxy z flip 5g",
  "samsung galaxy a51 5g uw",
  "samsung galaxy m51",
  "samsung galaxy note20",
  "samsung galaxy note20 5g",
  "samsung galaxy note20 ultra",
  "samsung galaxy note20 ultra 5g",
  "samsung galaxy a42 5g",
  "samsung galaxy s20 fe",
  "samsung galaxy s20 fe 5g",
  "samsung galaxy f41",
  "samsung galaxy m31 prime",
  "samsung galaxy a02s",
  "samsung galaxy a12",
  "samsung galaxy m21s",
  "samsung galaxy a02",
  "samsung galaxy a32 5g",
  "samsung galaxy m02s",
  "samsung galaxy s21 5g",
  "samsung galaxy s21+ 5g",
  "samsung galaxy s21 ultra 5g",
  "samsung galaxy a32",
  "samsung galaxy f62",
  "samsung galaxy m02",
  "samsung galaxy m12 (india)",
  "samsung galaxy m62",
  "samsung galaxy a52",
  "samsung galaxy a52 5g",
  "samsung galaxy a72",
  "samsung galaxy xcover 5",
  "samsung galaxy f02s",
  "samsung galaxy f12",
  "samsung galaxy m12",
  "samsung galaxy quantum 2",
  "samsung galaxy a22",
  "samsung galaxy a22 5g",
  "samsung galaxy m32",
  "samsung galaxy f22",
  "samsung galaxy m21 2021",
  "samsung galaxy a03s",
  "samsung galaxy a12 nacho",
  "samsung galaxy a52s 5g",
  "samsung galaxy m32 5g",
  "samsung galaxy z fold3 5g",
  "samsung galaxy f42 5g",
  "samsung galaxy m22",
  "samsung galaxy m52 5g",
  "sharp",
  "sharp sh530u",
  "sharp aquos crystal",
  "sharp aquos crystal 2",
  "sharp aquos xx",
  "sharp ms1",
  "sharp z2",
  "sharp z3",
  "sharp aquos s2",
  "sharp aquos s3",
  "sharp aquos s3 mini",
  "sharp aquos s3 high",
  "sharp aquos r2 compact",
  "sharp aquos zero",
  "sharp aquos v",
  "sharp aquos zero 2",
  "sony",
  "sony xperia 5 plus",
  "sony xperia c670x",
  "sony xperia h8541",
  "sony xperia m ultra",
  "sony xperia x ultra",
  "sony xperia z4 compact",
  "sony xperia z4 ultra",
  "sony xperia z4v",
  "sony xperia ion lte",
  "sony xperia neo l",
  "sony xperia j",
  "sony xperia tx",
  "sony xperia v",
  "sony xperia t lte",
  "sony xperia e dual",
  "sony xperia z",
  "sony xperia zl",
  "sony xperia l",
  "sony xperia sp",
  "sony xperia zr",
  "sony xperia c",
  "sony xperia m",
  "sony xperia z ultra",
  "sony xperia z1",
  "sony xperia e1",
  "sony xperia e1 dual",
  "sony xperia t2 ultra",
  "sony xperia t2 ultra dual",
  "sony xperia z1 compact",
  "sony xperia z1s",
  "sony xperia m2",
  "sony xperia m2 dual",
  "sony xperia z2",
  "sony xperia t3",
  "sony xperia z2a",
  "sony xperia c3",
  "sony xperia c3 dual",
  "sony xperia m2 aqua",
  "sony xperia e3",
  "sony xperia e3 dual",
  "sony xperia z3",
  "sony xperia z3 compact",
  "sony xperia z3 dual",
  "sony xperia z3v",
  "sony xperia e4",
  "sony xperia e4 dual",
  "sony xperia e4g",
  "sony xperia e4g dual",
  "sony xperia c4",
  "sony xperia c4 dual",
  "sony xperia z3+",
  "sony xperia z3+ dual",
  "sony xperia c5 ultra",
  "sony xperia c5 ultra dual",
  "sony xperia m5",
  "sony xperia m5 dual",
  "sony xperia z5",
  "sony xperia z5 compact",
  "sony xperia z5 dual",
  "sony xperia z5 premium",
  "sony xperia z5 premium dual",
  "sony xperia xa",
  "sony xperia xa dual",
  "sony xperia e5",
  "sony xperia xa ultra",
  "sony xperia x compact",
  "sony xperia xz",
  "sony xperia xa1",
  "sony xperia xa1 ultra",
  "sony xperia xz premium",
  "sony xperia xzs",
  "sony xperia l1",
  "sony xperia xa1 plus",
  "sony xperia xz1",
  "sony xperia xz1 compact",
  "sony xperia r1 (plus)",
  "sony xperia l2",
  "sony xperia xa2",
  "sony xperia xa2 ultra",
  "sony xperia xz2",
  "sony xperia xz2 compact",
  "sony xperia xz2 premium",
  "sony xperia xa2 plus",
  "sony xperia xz3",
  "sony xperia 1",
  "sony xperia 10",
  "sony xperia 10 plus",
  "sony xperia l3",
  "sony xperia 5",
  "sony xperia 10 ii",
  "sony xperia 1 ii",
  "sony xperia l4",
  "sony xperia pro",
  "sony xperia 5 ii",
  "sony xperia 10 iii",
  "sony xperia 1 iii",
  "sony xperia 5 iii",
  "sony xperia 10 iii lite",
  "sony ericsson",
  "sony ericsson ericsson xperia arc s",
  "sony ericsson ericsson xperia neo v",
  "sony ericsson ericsson xperia play",
  "sony ericsson ericsson xperia pro",
  "sony ericsson ericsson xperia ray",
  "sony ericsson ericsson xperia x10",
  "sony ericsson ericsson xperia x8",
  "vivo",
  "vivo xplay7",
  "vivo y51",
  "vivo xplay3s",
  "vivo y15 (2013)",
  "vivo y22",
  "vivo x3s",
  "vivo x5",
  "vivo xshot",
  "vivo y11",
  "vivo x5max",
  "vivo y27",
  "vivo y28",
  "vivo x5max+",
  "vivo x5pro",
  "vivo v1",
  "vivo y35",
  "vivo v1 max",
  "vivo y15s (2015)",
  "vivo y37",
  "vivo y31 (2015)",
  "vivo x6",
  "vivo x6plus",
  "vivo x6s",
  "vivo x6s plus",
  "vivo xplay5",
  "vivo xplay5 elite",
  "vivo v3",
  "vivo v3max",
  "vivo x7",
  "vivo x7 plus",
  "vivo v5",
  "vivo x9",
  "vivo x9 plus",
  "vivo xplay6",
  "vivo y67",
  "vivo v5 lite (vivo 1609)",
  "vivo v5 plus",
  "vivo y55s",
  "vivo y25",
  "vivo v5s",
  "vivo x9s",
  "vivo x9s plus",
  "vivo y69",
  "vivo v7+",
  "vivo x20",
  "vivo x20 plus",
  "vivo y65",
  "vivo v7",
  "vivo x20 plus ud",
  "vivo v9",
  "vivo x21 ud",
  "vivo v9 youth",
  "vivo y71",
  "vivo x21i",
  "vivo z1",
  "vivo nex a",
  "vivo nex s",
  "vivo v9 6gb",
  "vivo y81",
  "vivo z1i",
  "vivo v11 (v11 pro)",
  "vivo x23",
  "vivo y71i",
  "vivo y81i",
  "vivo z3",
  "vivo z3i",
  "vivo y91i",
  "vivo y93",
  "vivo y95",
  "vivo z1 lite",
  "vivo nex dual display",
  "vivo y93 (mediatek)",
  "vivo y93s",
  "vivo v15 pro",
  "vivo v15",
  "vivo x27",
  "vivo y91i (india)",
  "vivo x27 pro",
  "vivo y17",
  "vivo z3x",
  "vivo y15",
  "vivo z5x",
  "vivo y12",
  "vivo iqoo neo",
  "vivo s1",
  "vivo y90",
  "vivo z1pro",
  "vivo iqoo pro",
  "vivo iqoo pro 5g",
  "vivo v17 neo",
  "vivo nex 3",
  "vivo nex 3 5g",
  "vivo u10",
  "vivo v17 pro",
  "vivo z1x",
  "vivo iqoo neo 855",
  "vivo u3",
  "vivo y11 (2019)",
  "vivo s1 pro",
  "vivo s5",
  "vivo u20",
  "vivo v17",
  "vivo y19",
  "vivo y3 standard",
  "vivo z5i",
  "vivo iqoo neo 855 racing",
  "vivo x30",
  "vivo x30 pro",
  "vivo y9s",
  "vivo iqoo 3 5g",
  "vivo z6 5g",
  "vivo nex 3s 5g",
  "vivo s6 5g",
  "vivo iqoo neo3 5g",
  "vivo v19",
  "vivo y50",
  "vivo iqoo z1",
  "vivo x50 lite",
  "vivo y30",
  "vivo y70s",
  "vivo v19 neo",
  "vivo x50 5g",
  "vivo x50 pro",
  "vivo x50 pro+",
  "vivo z5x (2020)",
  "vivo iqoo u1",
  "vivo iqoo z1x",
  "vivo x50",
  "vivo y12i",
  "vivo y51s",
  "vivo iqoo 5 5g",
  "vivo iqoo 5 pro 5g",
  "vivo s1 prime",
  "vivo y20",
  "vivo y20i",
  "vivo x50e",
  "vivo iqoo u1x",
  "vivo x51 5g",
  "vivo y11s",
  "vivo y20s",
  "vivo y70",
  "vivo y12s",
  "vivo iqoo u3",
  "vivo y20 2021",
  "vivo y20a",
  "vivo iqoo 7",
  "vivo x60 pro+",
  "vivo y20g",
  "vivo y31",
  "vivo y31s",
  "vivo iqoo neo5",
  "vivo iqoo u3x",
  "vivo iqoo z3",
  "vivo s9",
  "vivo s9e",
  "vivo x60",
  "vivo x60 pro",
  "vivo y30g",
  "vivo y72 5g",
  "vivo v21e",
  "vivo x60t",
  "vivo y12s 2021",
  "vivo v21e 5g",
  "vivo x60t pro+",
  "vivo y53s",
  "vivo y70t",
  "vivo s10",
  "vivo s10 pro",
  "vivo y53s 4g",
  "vivo iqoo 8",
  "vivo iqoo 8 pro",
  "vivo y21",
  "vivo y33s",
  "vivo iqoo z5",
  "vivo x70 pro",
  "vivo x70 pro+",
  "vivo y21s",
  "xiaomi",
  "xiaomi mi 11x",
  "xiaomi mi 11x pro",
  "xiaomi mi 6c",
  "xiaomi mi 6 plus",
  "xiaomi mi max 4",
  "xiaomi mi max 4 pro",
  "xiaomi mi mix alpha",
  "xiaomi mi note plus",
  "xiaomi poco m3 pro 5g",
  "xiaomi redmi 20x",
  "xiaomi redmi pro 2",
  "xiaomi mi 1s",
  "xiaomi mi 2",
  "xiaomi mi 2a",
  "xiaomi mi 2s",
  "xiaomi mi 3",
  "xiaomi redmi 1s",
  "xiaomi mi 4",
  "xiaomi redmi note 4g",
  "xiaomi mi 4 lte",
  "xiaomi mi note",
  "xiaomi mi note pro",
  "xiaomi redmi 2",
  "xiaomi redmi 2a",
  "xiaomi mi 4i",
  "xiaomi redmi 2 prime",
  "xiaomi mi 4c",
  "xiaomi redmi 2 pro",
  "xiaomi redmi note 3 (mediatek)",
  "xiaomi redmi note prime",
  "xiaomi redmi 3",
  "xiaomi mi 4s",
  "xiaomi redmi 3 pro",
  "xiaomi redmi 3s",
  "xiaomi redmi 3x",
  "xiaomi redmi 3s prime",
  "xiaomi mi 5s",
  "xiaomi mi 5s plus",
  "xiaomi mi mix",
  "xiaomi mi note 2",
  "xiaomi redmi 4a",
  "xiaomi redmi 4 (china)",
  "xiaomi redmi 4 prime",
  "xiaomi redmi note 4",
  "xiaomi mi 5c",
  "xiaomi redmi note 4x",
  "xiaomi mi 6",
  "xiaomi mi max 2",
  "xiaomi redmi 4 (4x)",
  "xiaomi mi a1 (mi 5x)",
  "xiaomi mi mix 2",
  "xiaomi mi note 3",
  "xiaomi redmi 5a",
  "xiaomi redmi y1 lite",
  "xiaomi redmi y1 (note 5a)",
  "xiaomi redmi 5",
  "xiaomi redmi 5 plus (redmi note 5)",
  "xiaomi redmi note 5 pro",
  "xiaomi mi mix 2s",
  "xiaomi redmi note 5 ai dual camera",
  "xiaomi black shark",
  "xiaomi mi 8",
  "xiaomi mi 8 explorer",
  "xiaomi mi 8 se",
  "xiaomi redmi s2 (redmi y2)",
  "xiaomi redmi 6",
  "xiaomi redmi 6a",
  "xiaomi mi a2 lite (redmi 6 pro)",
  "xiaomi mi a2 (mi 6x)",
  "xiaomi mi max 3",
  "xiaomi pocophone f1",
  "xiaomi mi 8 lite",
  "xiaomi mi 8 pro",
  "xiaomi redmi note 6 pro",
  "xiaomi black shark helo",
  "xiaomi mi mix 3",
  "xiaomi mi play",
  "xiaomi redmi go",
  "xiaomi redmi note 7",
  "xiaomi mi 9",
  "xiaomi mi 9 explorer",
  "xiaomi mi 9 se",
  "xiaomi mi mix 3 5g",
  "xiaomi redmi note 7 pro",
  "xiaomi black shark 2",
  "xiaomi redmi y3",
  "xiaomi redmi 7a",
  "xiaomi redmi note 7s",
  "xiaomi mi 9t",
  "xiaomi black shark 2 pro",
  "xiaomi mi a3",
  "xiaomi mi cc9",
  "xiaomi mi cc9e",
  "xiaomi mi 9t pro",
  "xiaomi redmi note 8",
  "xiaomi redmi note 8 pro",
  "xiaomi mi 9 lite",
  "xiaomi mi 9 pro",
  "xiaomi mi 9 pro 5g",
  "xiaomi redmi 8a",
  "xiaomi redmi k20 pro premium",
  "xiaomi redmi 8",
  "xiaomi mi cc9 pro",
  "xiaomi mi note 10",
  "xiaomi mi note 10 pro",
  "xiaomi redmi note 8t",
  "xiaomi redmi k30",
  "xiaomi redmi k30 5g",
  "xiaomi mi 10 5g",
  "xiaomi mi 10 pro 5g",
  "xiaomi poco x2",
  "xiaomi redmi 8a dual",
  "xiaomi black shark 3",
  "xiaomi black shark 3 pro",
  "xiaomi mi 10 lite 5g",
  "xiaomi redmi k30 pro",
  "xiaomi redmi k30 pro zoom",
  "xiaomi redmi note 9 pro (india)",
  "xiaomi redmi note 9 pro max",
  "xiaomi redmi note 9s",
  "xiaomi mi 10 youth 5g",
  "xiaomi mi note 10 lite",
  "xiaomi redmi 8a pro",
  "xiaomi redmi note 9",
  "xiaomi redmi note 9 pro",
  "xiaomi poco f2 pro",
  "xiaomi redmi 10x 4g",
  "xiaomi redmi 10x 5g",
  "xiaomi redmi 10x pro 5g",
  "xiaomi redmi k30 5g racing",
  "xiaomi redmi k30i 5g",
  "xiaomi redmi 9",
  "xiaomi redmi 9a",
  "xiaomi redmi 9c",
  "xiaomi black shark 3s",
  "xiaomi poco m2 pro",
  "xiaomi mi 10 ultra",
  "xiaomi redmi 9c nfc",
  "xiaomi redmi 9 (india)",
  "xiaomi redmi 9 prime",
  "xiaomi redmi k30 ultra",
  "xiaomi mi 10t 5g",
  "xiaomi mi 10t lite 5g",
  "xiaomi mi 10t pro 5g",
  "xiaomi poco m2",
  "xiaomi poco x3",
  "xiaomi poco x3 nfc",
  "xiaomi redmi 9at",
  "xiaomi redmi 9i",
  "xiaomi poco c3",
  "xiaomi redmi k30s",
  "xiaomi poco m3",
  "xiaomi redmi note 9 4g",
  "xiaomi redmi note 9 5g",
  "xiaomi redmi note 9 pro 5g",
  "xiaomi mi 11",
  "xiaomi redmi 9 power",
  "xiaomi mi 10i 5g",
  "xiaomi redmi 9t",
  "xiaomi redmi note 9t",
  "xiaomi redmi k40",
  "xiaomi redmi k40 pro",
  "xiaomi redmi k40 pro+",
  "xiaomi black shark 4",
  "xiaomi black shark 4 pro",
  "xiaomi mi 10s",
  "xiaomi mi 11i",
  "xiaomi mi 11 lite",
  "xiaomi mi 11 lite 5g",
  "xiaomi mi 11 pro",
  "xiaomi mi 11 ultra",
  "xiaomi mi mix fold",
  "xiaomi poco f3",
  "xiaomi poco x3 pro",
  "xiaomi redmi note 10",
  "xiaomi redmi note 10 5g",
  "xiaomi redmi note 10 pro",
  "xiaomi redmi note 10 pro max",
  "xiaomi redmi note 10s",
  "xiaomi redmi note 10 pro (china)",
  "xiaomi poco f3 gt",
  "xiaomi poco x3 gt",
  "xiaomi redmi note 10t 5g",
  "xiaomi mix 4",
  "xiaomi redmi 10",
  "xiaomi 11 lite 5g ne",
  "xiaomi 11t",
  "xiaomi 11t pro",
  "xiaomi civi",
  "xiaomi poco c31",
  "xiaomi redmi 10 prime",
  "yota",
  "yota yotaphone",
  "yota yotaphone 2",
  "yota yotaphone 3",
  "zte",
  "zte blade v20",
  "zte hawkeye",
  "zte nubia x 5g",
  "zte open l",
  "zte grand x in",
  "zte anthem 4g",
  "zte blade iii",
  "zte grand era u895",
  "zte warp sequent",
  "zte groove x501",
  "zte kis iii v790",
  "zte v887",
  "zte v889m",
  "zte avid 4g",
  "zte blade c v807",
  "zte grand s",
  "zte grand x pro",
  "zte blade g v880g",
  "zte grand x quad v987",
  "zte blade g2",
  "zte blade q",
  "zte blade q maxi",
  "zte blade q mini",
  "zte nubia z5s mini nx403a",
  "zte grand s ii s291",
  "zte iconic phablet",
  "zte sonata 4g",
  "zte grand memo ii lte",
  "zte open c",
  "zte open ii",
  "zte nubia x6",
  "zte redbull v5 v9180",
  "zte star 1",
  "zte blade l2",
  "zte kis 3",
  "zte grand s pro",
  "zte nubia z7",
  "zte nubia z7 max",
  "zte nubia z7 mini",
  "zte nubia z5s mini nx405h",
  "zte blade vec 3g",
  "zte blade vec 4g",
  "zte kis 3 max",
  "zte zmax",
  "zte grand xmax",
  "zte zinger",
  "zte grand s ii",
  "zte grand x plus z826",
  "zte speed",
  "zte star 2",
  "zte blade q pro",
  "zte blade s6",
  "zte grand x max+",
  "zte imperial ii",
  "zte blade g",
  "zte blade g lux",
  "zte blade l3",
  "zte v5 lux",
  "zte blade l3 plus",
  "zte grand s3",
  "zte nubia z9 max",
  "zte nubia z9 mini",
  "zte blade s6 plus",
  "zte blade a410",
  "zte blade a460",
  "zte blade apex 3",
  "zte blade qlux 4g",
  "zte maven",
  "zte nubia my prague",
  "zte sonata 2",
  "zte axon lux",
  "zte axon pro",
  "zte blade d6",
  "zte boost max+",
  "zte grand x2",
  "zte obsidian",
  "zte axon elite",
  "zte zmax 2",
  "zte axon mini",
  "zte blade s7",
  "zte blade x3",
  "zte blade x5",
  "zte blade x9",
  "zte axon max",
  "zte avid plus",
  "zte blade a452",
  "zte blade v plus",
  "zte grand x 3",
  "zte nubia prague s",
  "zte blade v7",
  "zte blade v7 lite",
  "zte blade a910",
  "zte blade l5 plus",
  "zte blade v7 max",
  "zte nubia z11 mini",
  "zte axon 7",
  "zte grand x max 2",
  "zte blade a2",
  "zte blade a601",
  "zte nubia z11",
  "zte nubia z11 max",
  "zte blade a512",
  "zte blade l110 (a110)",
  "zte nubia n1",
  "zte zmax pro",
  "zte blade a610",
  "zte warp 7",
  "zte axon 7 mini",
  "zte grand x4",
  "zte nubia z11 mini s",
  "zte blade v8",
  "zte blade v8 pro",
  "zte blade a2 plus",
  "zte blade v8 lite",
  "zte blade v8 mini",
  "zte nubia n1 lite",
  "zte blade a520",
  "zte nubia m2",
  "zte nubia m2 lite",
  "zte nubia n2",
  "zte axon 7s",
  "zte max xl",
  "zte nubia z17 mini",
  "zte nubia m2 play",
  "zte nubia z17",
  "zte blade v7 plus",
  "zte maven 2",
  "zte blade a6",
  "zte nubia z17 lite",
  "zte tempo x",
  "zte axon m",
  "zte blade force",
  "zte blade x",
  "zte nubia z17 minis",
  "zte nubia z17s",
  "zte blade a3",
  "zte blade v9",
  "zte blade v9 vita",
  "zte tempo go",
  "zte nubia n3",
  "zte nubia v18",
  "zte nubia red magic",
  "zte nubia z18 mini",
  "zte axon 9 pro",
  "zte nubia z18",
  "zte nubia x",
  "zte nubia red magic mars",
  "zte blade a7 vita",
  "zte blade max view",
  "zte axon 10 pro",
  "zte axon 10 pro 5g",
  "zte blade v10",
  "zte blade v10 vita",
  "zte blade a3 (2019)",
  "zte blade l8",
  "zte blade a7",
  "zte nubia red magic 3",
  "zte nubia z20",
  "zte nubia red magic 3s",
  "zte blade 10 prime",
  "zte blade a7 prime",
  "zte axon 20 5g extreme",
  "zte axon 10s pro 5g",
  "zte axon 11 5g",
  "zte nubia red magic 5g",
  "zte nubia play",
  "zte axon 11 4g",
  "zte nubia red magic 5g lite",
  "zte nubia red magic 5s",
  "zte axon 20 5g",
  "zte axon 20 4g",
  "zte blade 20 pro 5g",
  "zte blade a7s 2020",
  "zte blade x1 5g",
  "zte nubia red magic 6",
  "zte nubia red magic 6 pro",
  "zte axon 30 pro 5g",
  "zte axon 30 ultra 5g",
  "zte nubia red magic 6r",
  "zte axon 30 5g",
  "zte blade v30",
  "zte blade v30 vita",
  "zte nubia red magic 6s",
  "zte nubia red magic 6s pro",
  "others",
]
