module.exports.cities = [
  {
    title: "Markazi",
    slug: "markazi",
    parentSlug: "",
    icon: "",
  },
  {
    title: "Ashtian",
    slug: "ashtian",
    parentSlug: "markazi",
    icon: "",
  },
  {
    title: "Arak",
    slug: "arak",
    parentSlug: "markazi",
    icon: "",
  },
  {
    title: "Tafresh",
    slug: "tafresh",
    parentSlug: "markazi",
    icon: "",
  },
  {
    title: "Khomain",
    slug: "khomain",
    parentSlug: "markazi",
    icon: "",
  },
  {
    title: "Varkaroud",
    slug: "varkaroud",
    parentSlug: "markazi",
    icon: "",
  },
  {
    title: "Delijan",
    slug: "delijan",
    parentSlug: "markazi",
    icon: "",
  },
  {
    title: "Zarandieh",
    slug: "zarandieh",
    parentSlug: "markazi",
    icon: "",
  },
  {
    title: "Saveh",
    slug: "saveh",
    parentSlug: "markazi",
    icon: "",
  },
  {
    title: "Shazand",
    slug: "shazand",
    parentSlug: "markazi",
    icon: "",
  },
  {
    title: "FARAHAN",
    slug: "farahan",
    parentSlug: "markazi",
    icon: "",
  },
  {
    title: "Mahalat",
    slug: "mahalat",
    parentSlug: "markazi",
    icon: "",
  },
  {
    title: "Komijan",
    slug: "komijan",
    parentSlug: "markazi",
    icon: "",
  },
  {
    title: "Gilan",
    slug: "gilan",
    parentSlug: "",
    icon: "",
  },
  {
    title: "Astara",
    slug: "astara",
    parentSlug: "gilan",
    icon: "",
  },
  {
    title: "Astaneh",
    slug: "astaneh",
    parentSlug: "gilan",
    icon: "",
  },
  {
    title: "Amlash",
    slug: "amlash",
    parentSlug: "gilan",
    icon: "",
  },
  {
    title: "Bandar Anzali",
    slug: "bandar-anzali",
    parentSlug: "gilan",
    icon: "",
  },
  {
    title: "Rasht",
    slug: "rasht",
    parentSlug: "gilan",
    icon: "",
  },
  {
    title: "Rezvanshahr",
    slug: "rezvanshahr",
    parentSlug: "gilan",
    icon: "",
  },
  {
    title: "Rudbar",
    slug: "rudbar",
    parentSlug: "gilan",
    icon: "",
  },
  {
    title: "Rudsar",
    slug: "rudsar",
    parentSlug: "gilan",
    icon: "",
  },
  {
    title: "Shafts",
    slug: "shafts",
    parentSlug: "gilan",
    icon: "",
  },
  {
    title: "Somesara",
    slug: "somesara",
    parentSlug: "gilan",
    icon: "",
  },
  {
    title: "Tvalsh",
    slug: "tvalsh",
    parentSlug: "gilan",
    icon: "",
  },
  {
    title: "Fooman",
    slug: "fooman",
    parentSlug: "gilan",
    icon: "",
  },
  {
    title: "LAHIJAN",
    slug: "lahijan",
    parentSlug: "gilan",
    icon: "",
  },
  {
    title: "Langerud",
    slug: "langerud",
    parentSlug: "gilan",
    icon: "",
  },
  {
    title: "Masal",
    slug: "masal",
    parentSlug: "gilan",
    icon: "",
  },
  {
    title: "Mazandaran",
    slug: "mazandaran",
    parentSlug: "",
    icon: "",
  },
  {
    title: "Amol",
    slug: "amol",
    parentSlug: "mazandaran",
    icon: "",
  },
  {
    title: "Babol",
    slug: "babol",
    parentSlug: "mazandaran",
    icon: "",
  },
  {
    title: "Babolsar",
    slug: "babolsar",
    parentSlug: "mazandaran",
    icon: "",
  },
  {
    title: "Behshahr",
    slug: "behshahr",
    parentSlug: "mazandaran",
    icon: "",
  },
  {
    title: "Tonkabon",
    slug: "tonkabon",
    parentSlug: "mazandaran",
    icon: "",
  },
  {
    title: "Juybar",
    slug: "juybar",
    parentSlug: "mazandaran",
    icon: "",
  },
  {
    title: "Ramsar",
    slug: "ramsar",
    parentSlug: "mazandaran",
    icon: "",
  },
  {
    title: "Infectious",
    slug: "infectious",
    parentSlug: "mazandaran",
    icon: "",
  },
  {
    title: "Savadkooh",
    slug: "savadkooh",
    parentSlug: "mazandaran",
    icon: "",
  },
  {
    title: "Abbas Abad",
    slug: "abbas-abad",
    parentSlug: "mazandaran",
    icon: "",
  },
  {
    title: "Fereidoon'kenar",
    slug: "fereidoon'kenar",
    parentSlug: "mazandaran",
    icon: "",
  },
  {
    title: "Qaemshahr",
    slug: "qaemshahr",
    parentSlug: "mazandaran",
    icon: "",
  },
  {
    title: "Mahmudabad",
    slug: "mahmudabad",
    parentSlug: "mazandaran",
    icon: "",
  },
  {
    title: "Nur",
    slug: "nur",
    parentSlug: "mazandaran",
    icon: "",
  },
  {
    title: "Noshahr",
    slug: "noshahr",
    parentSlug: "mazandaran",
    icon: "",
  },
  {
    title: "Chalus",
    slug: "chalus",
    parentSlug: "mazandaran",
    icon: "",
  },
  {
    title: "Kelardasht",
    slug: "kelardasht",
    parentSlug: "mazandaran",
    icon: "",
  },
  {
    title: "Galugah",
    slug: "galugah",
    parentSlug: "mazandaran",
    icon: "",
  },
  {
    title: "Este Azerbaijan",
    slug: "este-azerbaijan",
    parentSlug: "",
    icon: "",
  },
  {
    title: "Azarshahr",
    slug: "azarshahr",
    parentSlug: "este-azerbaijan",
    icon: "",
  },
  {
    title: "Osku",
    slug: "osku",
    parentSlug: "este-azerbaijan",
    icon: "",
  },
  {
    title: "Ahar",
    slug: "ahar",
    parentSlug: "este-azerbaijan",
    icon: "",
  },
  {
    title: "Bostanabad",
    slug: "bostanabad",
    parentSlug: "este-azerbaijan",
    icon: "",
  },
  {
    title: "BONAB",
    slug: "bonab",
    parentSlug: "este-azerbaijan",
    icon: "",
  },
  {
    title: "Tabriz",
    slug: "tabriz",
    parentSlug: "este-azerbaijan",
    icon: "",
  },
  {
    title: "Jolfa",
    slug: "jolfa",
    parentSlug: "este-azerbaijan",
    icon: "",
  },
  {
    title: "Sarab",
    slug: "sarab",
    parentSlug: "este-azerbaijan",
    icon: "",
  },
  {
    title: "Shabestar",
    slug: "shabestar",
    parentSlug: "este-azerbaijan",
    icon: "",
  },
  {
    title: "Ajabshir",
    slug: "ajabshir",
    parentSlug: "este-azerbaijan",
    icon: "",
  },
  {
    title: "Maragheh",
    slug: "maragheh",
    parentSlug: "este-azerbaijan",
    icon: "",
  },
  {
    title: "Marand",
    slug: "marand",
    parentSlug: "este-azerbaijan",
    icon: "",
  },
  {
    title: "Malakan",
    slug: "malakan",
    parentSlug: "este-azerbaijan",
    icon: "",
  },
  {
    title: "Mianeh",
    slug: "mianeh",
    parentSlug: "este-azerbaijan",
    icon: "",
  },
  {
    title: "Harris",
    slug: "harris",
    parentSlug: "este-azerbaijan",
    icon: "",
  },
  {
    title: "Hashtrood",
    slug: "hashtrood",
    parentSlug: "este-azerbaijan",
    icon: "",
  },
  {
    title: "Varzeghan",
    slug: "varzeghan",
    parentSlug: "este-azerbaijan",
    icon: "",
  },
  {
    title: "Charoymagh",
    slug: "charoymagh",
    parentSlug: "este-azerbaijan",
    icon: "",
  },
  {
    title: "Kalibar",
    slug: "kalibar",
    parentSlug: "este-azerbaijan",
    icon: "",
  },
]
